### ISSUE TITLE
Export Active Flight Track as CSV

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#103]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/103) by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

```
#!python

Traceback (most recent call last):
  File "/home/user/miniconda2/envs/mssenv/lib/python2.7/site-packages/mslib/msui/mss_pyui.py", line 341, in save_function_wrapper
    function(filename, self.active_flight_track.name, self.active_flight_track.waypoints)
  File "/home/user/miniconda2/envs/mssenv/lib/python2.7/site-packages/mslib/plugins/io/csv.py", line 9, in save_to_csv
    csv_writer = csv.writer(out_file, dialect='excel', delimiter=";", lineterminator="\n")
AttributeError: 'module' object has no attribute 'writer'
```

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

fixed by cs a732b04
