### ISSUE TITLE
clone project fatal error

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1058]
run into this wanted to clone to the TEMPLATE

```
Fatal error in MSS 4.0.3. on Linux-5.4.0-77-generic-x86_64-with-glibc2.27
Python 3.9.5 | packaged by conda-forge | (default, Jun 19 2021, 00:32:32) 
[GCC 9.3.0]

Please report bugs in MSS to https://github.com/Open-MSS/MSS

Information about the fatal error:

Traceback (most recent call last):
  File "/home/reimar/miniconda3/envs/mssenv/lib/python3.9/site-packages/mslib/msui/mscolab_admin_window.py", line 274, in import_permissions
    res = res.json()
  File "/home/reimar/miniconda3/envs/mssenv/lib/python3.9/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/reimar/miniconda3/envs/mssenv/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/reimar/miniconda3/envs/mssenv/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/reimar/miniconda3/envs/mssenv/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by ReimarBauer** [comment]
If I need admin rights on the project I want to clone from. So I should only see those in the pull down where I can get access to the member state.

If there is a TEMPLATE project used all who wants to inherit from that needs admin role there.

As a collaborator sees also all member states this should be possible to use for this role too.

**Comment by ReimarBauer** [comment]
This needs first a unit test for describing the real cause before fixing. 

This problem did not happen regularly.

**Comment by ReimarBauer** [comment]
likly a networking problem, reopen when there are more details
