### ISSUE TITLE
Elevations not present for some layers

### ISSUE THREAD

**Issue by Marilyth** [Open-MSS/MSS#1060]
I am not sure if this is caused by the gallery or by faulty data, but during testing of the gallery on the campaigns2019 server these errors keep popping up:

```Traceback (most recent call last):
  File "/home/mss-campaigns2019/src/Marilyth/MSS/mslib/mswms/wms.py", line 308, in generate_gallery
    add_image(plot_driver.plot(), plot_object, generate_code, sphinx, url_prefix=url_prefix)
  File "/home/mss-campaigns2019/src/Marilyth/MSS/mslib/mswms/mss_plot_driver.py", line 538, in plot
    image = self.plot_object.plot_vsection(data, self.lats, self.lons,
  File "/home/mss-campaigns2019/src/Marilyth/MSS/mslib/mswms/mpl_vsec.py", line 188, in plot_vsection
    UR(self.driver.vert_units).check("[temperature]")):
  File "/home/mss-campaigns2019/miniconda3/envs/stable/lib/python3.9/site-packages/pint/registry.py", line 1263, in parse_expression
    return build_eval_tree(gen).evaluate(
  File "/home/mss-campaigns2019/miniconda3/envs/stable/lib/python3.9/site-packages/pint/pint_eval.py", line 92, in evaluate
    left = self.left.evaluate(define_op, bin_op, un_op)
  File "/home/mss-campaigns2019/miniconda3/envs/stable/lib/python3.9/site-packages/pint/pint_eval.py", line 102, in evaluate
    return define_op(self.left)
  File "/home/mss-campaigns2019/miniconda3/envs/stable/lib/python3.9/site-packages/pint/registry.py", line 1264, in <lambda>
    lambda x: self._eval_token(x, case_sensitive=case_sensitive, **values)
  File "/home/mss-campaigns2019/miniconda3/envs/stable/lib/python3.9/site-packages/pint/registry.py", line 1159, in _eval_token
    {self.get_name(token_text, case_sensitive=case_sensitive): 1}
  File "/home/mss-campaigns2019/miniconda3/envs/stable/lib/python3.9/site-packages/pint/registry.py", line 643, in get_name
    raise UndefinedUnitError(name_or_alias)
pint.errors.UndefinedUnitError: 'unknown' is not defined in the unit registry
```

and

```Traceback (most recent call last):
  File "/home/mss-campaigns2019/src/Marilyth/MSS/mslib/mswms/wms.py", line 294, in generate_gallery
    elevations = plot_object.get_elevations()
  File "/home/mss-campaigns2019/src/Marilyth/MSS/mslib/mswms/mss_2D_sections.py", line 165, in get_elevations
    return [str(x) for x in self.driver.get_elevations(self._vert_type)]
  File "/home/mss-campaigns2019/src/Marilyth/MSS/mslib/mswms/mss_plot_driver.py", line 316, in get_elevations
    return self.data_access.get_elevations(vert_type)
  File "/home/mss-campaigns2019/src/Marilyth/MSS/mslib/mswms/dataaccess.py", line 366, in get_elevations
    return self._elevations[vert_type]["levels"]
KeyError: 'pl'
```

My first guess is faulty data, since self._elevations seems to not be filled up, paired with a unknown units warning during a vert_units check.
It would be nice if you could also have a look at this @joernu76

**Comment by joernu76** [comment]
Starting up the server does not show errors. 
```
(stable) mss-campaigns2019@icg1317:~/CAMPAIGNS2019/config$ PYTHONPATH=. mswms --debug >log 2>&1
```

**Comment by joernu76** [comment]
At least not with the stable version. I'll try your code.

**Comment by joernu76** [comment]
Mmmh, I get different errors. Can you create an environment where I can reproduce the error?

**Comment by ReimarBauer** [comment]
in stable environment we have the version of Mays repo builded

````
mamba list | grep mss
# packages in environment at /home/mss-campaigns2019/miniconda3/envs/stable:
mss-test                  alpha                 py39_1003    file:///home/mss-campaigns2019/miniconda3/conda-bld
```

**Comment by joernu76** [comment]
OK, one step further. If a variable has no "units" attribute, mss will assign the units the "unknown units" string. But such variables will be "discarded" in the dataaccess class. So you should not "encounter" them, even if present.

**Comment by joernu76** [comment]
OK, the stable version does "something". Could use a bit more of debug messages to get an impression of what it is doing.

**Comment by joernu76** [comment]
OK, can reproduce the problem.

**Comment by ReimarBauer** [comment]
see into the src folder there is the version used

**Comment by Marilyth** [comment]
There are a bunch of files without units or None units. These aren't all but should bring the point across.
```
INFO: Vert units of ['/srv/mss/CAMPAIGNS2019/mssdata/analysis/2019-11-27.an.ml.nc', '/srv/mss/CAMPAIGNS2019/mssdata/analysis/2019-11-27.an.sfc.nc'] unknown units
INFO: Vert units of ['/srv/mss/CAMPAIGNS2019/mssdata/transfer/2019-11-05T00:00:00.an.ml.nc', '/srv/mss/CAMPAIGNS2019/mssdata/transfer/2019-11-05T00:00:00.an.sfc.nc'] unknown units
INFO: Vert units of ['/srv/mss/CAMPAIGNS2019/mssdata/analysis/2019-11-27.an.sfc.nc'] None
INFO: Vert units of ['/srv/mss/CAMPAIGNS2019/mssdata/analysis/2019-11-27.an.bt.nc'] None
INFO: Vert units of ['/srv/mss/CAMPAIGNS2019/mssdata/transfer/2019-11-05T00:00:00.an.sfc.nc'] None
INFO: Vert units of ['/srv/mss/CAMPAIGNS2019/mssdata/airs/2019-11-27T00:00:00_AIRS_filt_tracks.nc'] None
INFO: Vert units of ['/srv/mss/CAMPAIGNS2019/mssdata/airs/2019-11-27T00:00:00_AIRS_filt_all.nc'] None
```

**Comment by joernu76** [comment]
All variables of /srv/mss/CAMPAIGNS2019/mssdata/analysis/2019-11-27.an.bt.nc have units:

ncdump -h /srv/mss/CAMPAIGNS2019/mssdata/analysis/2019-11-27.an.bt.nc

```
variables:
	float BTemp_ecmwf_res_15mu_high(time, lat, lon) ;
		BTemp_ecmwf_res_15mu_high:standard_name = "brightness_temperature_residual_15mu_high" ;
		BTemp_ecmwf_res_15mu_high:long_name = "ECMWF set to look like Brightness T at 15mu_high AIRS T" ;
		BTemp_ecmwf_res_15mu_high:units = "kelvin" ;
	float BTemp_ecmwf_res_15mu_low(time, lat, lon) ;
		BTemp_ecmwf_res_15mu_low:standard_name = "brightness_temperature_residual_15mu_low" ;
		BTemp_ecmwf_res_15mu_low:long_name = "ECMWF set to look like Brightness T at 15mu_low AIRS T" ;
		BTemp_ecmwf_res_15mu_low:units = "kelvin" ;
	float BTemp_ecmwf_res_4mu(time, lat, lon) ;
		BTemp_ecmwf_res_4mu:standard_name = "brightness_temperature_residual_4mu" ;
		BTemp_ecmwf_res_4mu:long_name = "ECMWF set to look like Brightness T at 4mu AIRS T" ;
		BTemp_ecmwf_res_4mu:units = "kelvin" ;
	double lat(lat) ;
		lat:standard_name = "latitude" ;
		lat:long_name = "latitude" ;
		lat:units = "degrees_north" ;
	double lon(lon) ;
		lon:standard_name = "longitude" ;
		lon:long_name = "longitude" ;
		lon:units = "degrees_east" ;
	double time(time) ;
		time:standard_name = "time" ;
		time:long_name = "time of overpass is 05:30 UTC" ;
		time:units = "hours since 2019-07-01T00:00:00" ;

// global attributes:
```

**Comment by joernu76** [comment]
Don't see a problem with the others either.

Maybe it happens with plots not associated to a particular elevation level? Cloud cover comes to mind.

**Comment by joernu76** [comment]
Ah, I see. The unknown unit error occurs for *Vertical Sections" of *model level" data.
Yes. The vertical axis has indeed no known or sensbile units in that particular case.

**Comment by joernu76** [comment]
I added that error.

**Comment by Marilyth** [comment]
Does that also explain the absence of self._elevations for the HS layers? (See second traceback)

**Comment by joernu76** [comment]
Maybe. One step at a time.
I propose this fix
```
diff --git a/mslib/netCDF4tools.py b/mslib/netCDF4tools.py
index 248bb07a..11d7b342 100644
--- a/mslib/netCDF4tools.py
+++ b/mslib/netCDF4tools.py
@@ -111,7 +111,7 @@ def identify_vertical_axis(dataset):
         name, var = identify_variable(dataset, standard_name)
         orientation = hybrid_orientation(var)
         if var is not None:
-            units = getattr(var, "units", "unknown units")
+            units = getattr(var, "units", "dimensionless")
             result.append((name, var, orientation, units, layertype))
     if len(result) == 0:
         return None, None, None, None, "sfc"
```
Seems safer...?

**Comment by joernu76** [comment]
The gallery is pretty nice for debugging plotting plugins :-)

**Comment by joernu76** [comment]
In case that the plot supports styles, you should select one (first?). I have at least one plot bugging our because none of the three styles was selected.

**Comment by Marilyth** [comment]
style="default" is always passed as an argument. I suppose taking the first style instead would work better.

**Comment by joernu76** [comment]
There may be no styles as well. Certainly so far, we do not enforce a "default" style being present.

**Comment by joernu76** [comment]
Aannnd another bug. Strange that it does not trigger normally.
This should fix the remaining problems:

```
diff --git a/mslib/mswms/dataaccess.py b/mslib/mswms/dataaccess.py
index 20c92d82..4ab0ff6b 100644
--- a/mslib/mswms/dataaccess.py
+++ b/mslib/mswms/dataaccess.py
@@ -225,7 +225,6 @@ class DefaultDataAccess(NWPDataAccess):
                 raise ValueError(f"variable type {vartype} not available for variable {variable}")
 
     def _parse_file(self, filename):
-        elevations = {"levels": [], "units": None}
         with netCDF4.Dataset(os.path.join(self._root_path, filename)) as dataset:
 
             time_name, time_var = netCDF4tools.identify_CF_time(dataset)
@@ -260,6 +259,8 @@ class DefaultDataAccess(NWPDataAccess):
                     if elevations["units"] != self._elevations[vert_type]["units"]:
                         raise IOError(f"vertical level units do not match previous "
                                       f"file '{self._elevations[vert_type]['filename']}'")
+                else:
+                    self._elevations[vert_type] = elevations
 
             standard_names = []
             for ncvarname, ncvar in dataset.variables.items():
```

**Comment by joernu76** [comment]
I can prepare a fix for develop if you like.

**Comment by Marilyth** [comment]
That would be great. I am glad the bugs were not caused by the plot gallery.

**Comment by joernu76** [comment]
They discovered some. A nice side-effect is that one can easily test all plots of the existing server including all hacked-in plotting classes. Very useful!

**Comment by ReimarBauer** [comment]
I would prefer to have this in stable @joernu76

**Comment by joernu76** [comment]
The one bug isn't even in stable and the other "simply" skips a test the first time a file is checked.
