### ISSUE TITLE
pyproj 3.1.0 shows a failing test

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1081]
```
mslib/msui/_tests/test_topview.py F                                      [100%]

=================================== FAILURES ===================================
___________________ Test_MSSTopViewWindow.test_insert_point ____________________

self = <test_topview.Test_MSSTopViewWindow object at 0x7f04081424c0>
mockbox = <MagicMock name='QMessageBox' id='139655295125824'>

    @mock.patch("PyQt5.QtWidgets.QMessageBox")
    def test_insert_point(self, mockbox):
        """
        Test inserting a point inside and outside the canvas
        """
        self.window.mpl.navbar._actions['insert_wp'].trigger()
        QtWidgets.QApplication.processEvents()
        assert len(self.window.waypoints_model.waypoints) == 3
        QtTest.QTest.mouseClick(self.window.mpl.canvas, QtCore.Qt.LeftButton)
        QtWidgets.QApplication.processEvents()
        assert len(self.window.waypoints_model.waypoints) == 4
        QtTest.QTest.mouseClick(self.window.mpl.canvas, QtCore.Qt.LeftButton, pos=QtCore.QPoint(1, 1))
        QtWidgets.QApplication.processEvents()
        assert len(self.window.waypoints_model.waypoints) == 4
        QtTest.QTest.mouseClick(self.window.mpl.canvas, QtCore.Qt.LeftButton)
        # click again on same position
        QtWidgets.QApplication.processEvents()
        assert len(self.window.waypoints_model.waypoints) == 5
>       assert mockbox.critical.call_count == 0
E       AssertionError: assert 1 == 0
E        +  where 1 = <MagicMock name='QMessageBox.critical' id='139655292135072'>.call_count
E        +    where <MagicMock name='QMessageBox.critical' id='139655292135072'> = <MagicMock name='QMessageBox' id='139655295125824'>.critical

mslib/msui/_tests/test_topview.py:143: AssertionError
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/home/reimar/PycharmProjects/2021/aravindm711/MSS/mslib/msui/mpl_pathinteractor.py", line 441, in qt_insert_remove_point_listener
    self.pathpatch.get_path().update_from_WaypointsTableModel(self.waypoints_model)
  File "/home/reimar/PycharmProjects/2021/aravindm711/MSS/mslib/msui/mpl_pathinteractor.py", line 299, in update_from_WaypointsTableModel
    x, y = self.map.gcpoints_path(lons, lats)
  File "/home/reimar/PycharmProjects/2021/aravindm711/MSS/mslib/msui/mpl_map.py", line 561, in gcpoints_path
    lonlats = gc.npts(lons[i], lats[i], lons[i + 1], lats[i + 1], npoints)
  File "/home/reimar/miniconda3/envs/mssdev/lib/python3.9/site-packages/pyproj/geod.py", line 368, in npts
    res = self._inv_or_fwd_intermediate(
  File "pyproj/_geod.pyx", line 243, in pyproj._geod.Geod._inv_or_fwd_intermediate
pyproj.exceptions.GeodError: inv_intermediate: npts and del_s are mutually exclusive, only one of them must be != 0.
------------------------------ Captured log call -------------------------------
2021-07-13 10:51:44 CRITICAL MSS Version: 4.0.0.
2021-07-13 10:51:44 CRITICAL Python Version: 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:46) 
[GCC 9.3.0]
2021-07-13 10:51:44 CRITICAL Platform: Linux-5.4.0-77-generic-x86_64-with-glibc2.27 (('64bit', 'ELF'))
2021-07-13 10:51:44 CRITICAL Fatal error: Traceback (most recent call last):
  File "/home/reimar/PycharmProjects/2021/aravindm711/MSS/mslib/msui/mpl_pathinteractor.py", line 441, in qt_insert_remove_point_listener
    self.pathpatch.get_path().update_from_WaypointsTableModel(self.waypoints_model)
  File "/home/reimar/PycharmProjects/2021/aravindm711/MSS/mslib/msui/mpl_pathinteractor.py", line 299, in update_from_WaypointsTableModel
    x, y = self.map.gcpoints_path(lons, lats)
  File "/home/reimar/PycharmProjects/2021/aravindm711/MSS/mslib/msui/mpl_map.py", line 561, in gcpoints_path
    lonlats = gc.npts(lons[i], lats[i], lons[i + 1], lats[i + 1], npoints)
  File "/home/reimar/miniconda3/envs/mssdev/lib/python3.9/site-packages/pyproj/geod.py", line 368, in npts
    res = self._inv_or_fwd_intermediate(
  File "pyproj/_geod.pyx", line 243, in pyproj._geod.Geod._inv_or_fwd_intermediate
pyproj.exceptions.GeodError: inv_intermediate: npts and del_s are mutually exclusive, only one of them must be != 0.
=============================== warnings summary ===============================
../../../../miniconda3/envs/mssdev/lib/python3.9/site-packages/future/standard_library/__init__.py:65
  /home/reimar/miniconda3/envs/mssdev/lib/python3.9/site-packages/future/standard_library/__init__.py:65: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

mslib/msui/_tests/test_tableview.py: 201 warnings
  /home/reimar/PycharmProjects/2021/aravindm711/MSS/mslib/msui/flighttrack.py:203: DeprecationWarning: an integer is required (got type ItemFlags).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
    return QtCore.Qt.ItemFlags(

mslib/msui/_tests/test_tableview.py: 261 warnings
  /home/reimar/PycharmProjects/2021/aravindm711/MSS/mslib/msui/flighttrack.py:208: DeprecationWarning: an integer is required (got type ItemFlags).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
    return QtCore.Qt.ItemFlags(

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================== short test summary info ============================
FAILED mslib/msui/_tests/test_topview.py::Test_MSSTopViewWindow::test_insert_point

```

**Comment by Marilyth** [comment]
This was already fixed here https://github.com/Open-MSS/MSS/commit/302a18651162b16898562bd2d26e42fb126e7c74
pyproj 3.1.0 is also running on the Docker containers for a month without issues.
It seems like you are running a pretty old version? (4.0.0)

**Comment by ReimarBauer** [comment]
ok, missed that option :)

**Comment by ReimarBauer** [comment]
same reason as https://github.com/Open-MSS/MSS/issues/1032
