### ISSUE TITLE
mss 5.0 requires python >=3.7

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1117]
With the metpy depency we have to skip py3.6 on all platforms

```
+ mswms -h
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/mss_1627921693786/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/mswms", line 7, in <module>
    from mslib.mswms.mswms import main
  File "/home/conda/feedstock_root/build_artifacts/mss_1627921693786/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.6/site-packages/mslib/mswms/mswms.py", line 33, in <module>
    from mslib.mswms.wms import mss_wms_settings, server
  File "/home/conda/feedstock_root/build_artifacts/mss_1627921693786/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.6/site-packages/mslib/mswms/wms.py", line 63, in <module>
    from mslib.utils import conditional_decorator
  File "/home/conda/feedstock_root/build_artifacts/mss_1627921693786/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.6/site-packages/mslib/utils.py", line 36, in <module>
    from metpy.units import units
  File "/home/conda/feedstock_root/build_artifacts/mss_1627921693786/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.6/site-packages/metpy/__init__.py", line 35, in <module>
    from .xarray import *  # noqa: F401, F403, E402
  File "/home/conda/feedstock_root/build_artifacts/mss_1627921693786/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.6/site-packages/metpy/xarray.py", line 28, in <module>
    import xarray as xr
  File "/home/conda/feedstock_root/build_artifacts/mss_1627921693786/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.6/site-packages/xarray/__init__.py", line 3, in <module>
    from . import testing, tutorial, ufuncs
  File "/home/conda/feedstock_root/build_artifacts/mss_1627921693786/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.6/site-packages/xarray/testing.py", line 9, in <module>
    from xarray.core.dataarray import DataArray
  File "/home/conda/feedstock_root/build_artifacts/mss_1627921693786/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.6/site-packages/xarray/core/dataarray.py", line 24, in <module>
    from . import (
  File "/home/conda/feedstock_root/build_artifacts/mss_1627921693786/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.6/site-packages/xarray/core/computation.py", line 4
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
Tests failed for mss-5.0.0-py36h5fab9bb_0.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
WARNING:conda_build.build:Tests failed for mss-5.0.0-py36h5fab9bb_0.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
WARNING conda_build.build:tests_failed(2955): Tests failed for mss-5.0.0-py36h5fab9bb_0.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
```

**Comment by ReimarBauer** [comment]
xarray added the dependency to python >=3.7 
This is used by metpy.

- https://github.com/conda-forge/xarray-feedstock/issues/65
- https://github.com/conda-forge/metpy-feedstock/issues/45
- https://github.com/conda-forge/xarray-feedstock/blob/master/recipe/meta.yaml

**Comment by ReimarBauer** [comment]
We should add the minimum python version to our docs.

**Comment by ReimarBauer** [comment]
With the current update/install procedure we will get always a version of MSS independent if we know what the minimum python version is.

We have not any requires ... line in the current doc and won't start this now.
