### ISSUE TITLE
traceback using on old mscolab server, migrate database

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1198]
trying the development branch on an old mscolab server gives a traceback on login. This happens because the database definition did not match. 

Also setting up gravatar Url does not make a difference. There are also other changes in the database e.g. category was added.  

We may be need a hint for the user that the server has a different version.  We have to check if we can show a default.

```
Fatal error in MSS 5.0.1. on Linux-5.4.0-81-generic-x86_64-with-glibc2.27
Python 3.9.6 | packaged by conda-forge | (default, Jul 11 2021, 03:39:48) 
[GCC 9.3.0]

Please report bugs in MSS to https://github.com/Open-MSS/MSS

Information about the fatal error:

Traceback (most recent call last):
  File "/home/reimar/PycharmProjects/MSS/mslib/msui/mscolab.py", line 488, in after_login
    self.conn = sc.ConnectionManager(self.token, user=self.user, mscolab_server_url=self.mscolab_server_url)
  File "/home/reimar/PycharmProjects/MSS/mslib/msui/socket_control.py", line 56, in __init__
    self.sio.connect(self.mscolab_server_url)
  File "/home/reimar/miniconda3/envs/mssdev/lib/python3.9/site-packages/socketio/client.py", line 329, in connect
    raise exceptions.ConnectionError(exc.args[0]) from None
socketio.exceptions.ConnectionError: Unexpected status code 400 in server response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/reimar/PycharmProjects/MSS/mslib/msui/mscolab.py", line 276, in login_handler
    self.mscolab.after_login(emailid, self.mscolab_server_url, r)
  File "/home/reimar/PycharmProjects/MSS/mslib/msui/mscolab.py", line 492, in after_login
    self.logout()
  File "/home/reimar/PycharmProjects/MSS/mslib/msui/mscolab.py", line 1534, in logout
    if self.gravatar is not None:
AttributeError: 'MSSMscolab' object has no attribute 'gravatar'
```

**Comment by ReimarBauer** [comment]
We have so many changes this needs a database migration or a reset. An old server is not compatible.

**Comment by ReimarBauer** [comment]
some documentation for postgres
https://www.citusdata.com/blog/2021/02/20/faster-data-migrations-in-postgres/

**Comment by ReimarBauer** [comment]
The gravatar problem was addressed in
https://github.com/Open-MSS/MSS/issues/1245
