### ISSUE TITLE
adding/revoking permissions have to add/remove flightpathes

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1203]
In develop to 6.0 revoking permissions don't remove flightpathes from the project list and also don't remove flightpathes from opened views. In the released version the windows were closed for the case that no further access was given.

Giving permissions did not update flightpathes on the project list. A toggle between categories does a manual update. This needs to get automated again.

**Comment by ReimarBauer** [comment]
identified  problems


- the view did not clean the wp model when permissions revoked  (./)
- revoking an operation and adding again shows an error. (./)
- toggleing between local and operation did not change viewer permissions (./)
- permission viewer shows a fatal error on opening topview with that permission:  (./)

Python 3.9.7 | packaged by conda-forge | (default, Sep  2 2021, 17:58:34) 
[GCC 9.4.0]

Please report bugs in MSS to https://github.com/Open-MSS/MSS

Information about the fatal error:

Traceback (most recent call last):
  File "/home/reimar/PycharmProjects/MSS/mslib/msui/mss_pyui.py", line 788, in create_view_handler
    self.mscolab.create_view_msc(_type)
  File "/home/reimar/PycharmProjects/MSS/mslib/msui/mscolab.py", line 1456, in create_view_msc
    self.disable_navbar_action_buttons(_type, view_window)
  File "/home/reimar/PycharmProjects/MSS/mslib/msui/mscolab.py", line 1469, in disable_navbar_action_buttons
    actions = view_window.mpl.navbar.actions()
AttributeError: 'NoneType' object has no attribute 'mpl'
```
