### ISSUE TITLE
websocket-client problem with a gunicorn server

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1242]
```
Information about the fatal error:

Traceback (most recent call last):
  File "/home/reimar/PycharmProjects/MSS/mslib/msui/mscolab.py", line 733, in add_operation
    self.conn.handle_new_operation(op_id)
  File "/home/reimar/PycharmProjects/MSS/mslib/msui/socket_control.py", line 144, in handle_new_operation
    self.sio.emit('add-user-to-operation', {
  File "/home/reimar/miniconda3/envs/mssdev/lib/python3.9/site-packages/socketio/client.py", line 384, in emit
    raise exceptions.BadNamespaceError(
socketio.exceptions.BadNamespaceError: / is not a connected namespace.
```

**Comment by ReimarBauer** [comment]
may be this is related to websocket-client 1.2.1 I've installed for testing. removing it.

**Comment by ReimarBauer** [comment]
looks like installing websocket-client 1.2.1 from pypi causes these problems. Without also MSS has faster reaction times.
