### ISSUE TITLE
hint for old clients with new MSC Servers and new clients with old servers.

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1247]
Because of the refactoring of the models of MSColab 6.0 older clients are incompatible. Also the database has more attributes.

We have to show a warning to the user.

**Comment by ReimarBauer** [comment]
When an new client tries to connect to an old mscolab server, the server knows the reason
```
ERROR:engineio.server:Invalid session fcdcc714682640f68d2b6fc81646e6fb (further occurrences of this error will be logged with level INFO)
ERROR:engineio.server:The client is using an unsupported version of the Socket.IO or Engine.IO protocols (further occurrences of this error will be logged with level INFO)
```

**Comment by ReimarBauer** [comment]
When an old client logs in into a new server then the login works but the traceback occures.

```

Traceback (most recent call last):
  File "/home/reimar/miniconda3/envs/mssenv/lib/python3.9/site-packages/mslib/msui/mscolab.py", line 728, in authorize
    self.after_authorize(emailid, r)
  File "/home/reimar/miniconda3/envs/mssenv/lib/python3.9/site-packages/mslib/msui/mscolab.py", line 737, in after_authorize
    self.add_projects()
  File "/home/reimar/miniconda3/envs/mssenv/lib/python3.9/site-packages/mslib/msui/mscolab.py", line 757, in add_projects
    _json = json.loads(r.text)
  File "/home/reimar/miniconda3/envs/mssenv/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/reimar/miniconda3/envs/mssenv/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/reimar/miniconda3/envs/mssenv/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
