### ISSUE TITLE
 'NoneType' object has no attribute 'close'

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1261]
```
Fatal error in MSS 5.0.2. on Linux-5.4.0-87-generic-x86_64-with-glibc2.27
Python 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:20:46) 
[GCC 9.4.0]

Please report bugs in MSS to https://github.com/Open-MSS/MSS

Information about the fatal error:

Traceback (most recent call last):
  File "/home/reimar/PycharmProjects/MSS/mslib/msui/mscolab.py", line 286, in login_server_auth
    self.mscolab.after_login(emailid, self.mscolab_server_url, r)
  File "/home/reimar/PycharmProjects/MSS/mslib/msui/mscolab.py", line 481, in after_login
    self.connect_window.close()
AttributeError: 'NoneType' object has no attribute 'close'
```

**Comment by ReimarBauer** [comment]
can't reproduce.
