### ISSUE TITLE
problem with waypoints_interactor

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1266]
found by tutorial_views
```
INFO: MSS Version: 5.0.2.
INFO: Python Version: 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:20:46) 
[GCC 9.4.0]
INFO: Platform: Linux-5.4.0-87-generic-x86_64-with-glibc2.27 (('64bit', 'ELF'))
ERROR: 
ERROR: 
ERROR: 
Traceback (most recent call last):
  File "/home/reimar/miniconda3/envs/mssdev/lib/python3.9/site-packages/matplotlib/cbook/__init__.py", line 270, in process
    func(*args, **kwargs)
  File "/home/reimar/PycharmProjects/MSS/mslib/msui/mpl_qtwidget.py", line 412, in mouse_move
    (lat, lon, alt), _ = self.canvas.waypoints_interactor.get_lat_lon(event)
ValueError: not enough values to unpack (expected 3, got 2)
Traceback (most recent call last):
  File "/home/reimar/miniconda3/envs/mssdev/lib/python3.9/site-packages/matplotlib/cbook/__init__.py", line 270, in process
    func(*args, **kwargs)
  File "/home/reimar/PycharmProjects/MSS/mslib/msui/mpl_qtwidget.py", line 412, in mouse_move
    (lat, lon, alt), _ = self.canvas.waypoints_interactor.get_lat_lon(event)
ValueError: not enough values to unpack (expected 3, got 2)
Traceback (most recent call last):
  File "/home/reimar/miniconda3/envs/mssdev/lib/python3.9/site-packages/matplotlib/cbook/__init__.py", line 270, in process
    func(*args, **kwargs)
  File "/home/reimar/PycharmProjects/MSS/mslib/msui/mpl_qtwidget.py", line 412, in mouse_move
    (lat, lon, alt), _ = self.canvas.waypoints_interactor.get_lat_lon(event)
ValueError: not enough values to unpack (expected 3, got 2)
Traceback (most recent call last):
  File "/home/reimar/miniconda3/envs/mssdev/lib/python3.9/site-packages/matplotlib/cbook/__init__.py", line 270, in process
    func(*args, **kwargs)
  File "/home/reimar/PycharmProjects/MSS/mslib/msui/mpl_qtwidget.py", line 412, in mouse_move
    (lat, lon, alt), _ = self.canvas.waypoints_interactor.get_lat_lon(event)
ValueError: not enough values to unpack (expected 3, got 2)
Traceback (most recent call last):
  File "/home/reimar/miniconda3/envs/mssdev/lib/python3.9/site-packages/matplotlib/cbook/__init__.py", line 270, in process
    func(*args, **kwargs)
  File "/home/reimar/PycharmProjects/MSS/mslib/msui/mpl_qtwidget.py", line 412, in mouse_move
    (lat, lon, alt), _ = self.canvas.waypoints_interactor.get_lat_lon(event)
ValueError: not enough values to unpack (expected 3, got 2)
```

**Comment by ReimarBauer** [comment]
reproduced on sideview with mouseover but not always this occures
