### ISSUE TITLE
Fatal error for new users after login because of no operation

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1285]
on a resetted db by
```
python mslib/mscolab/mscolab.py db --reset
```
create a user and login gives this traceback

It did not raise for  a user with operations
```
Fatal error in MSS 6.0.0. on Linux-5.4.0-87-generic-x86_64-with-glibc2.27
Python 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:20:46) 
[GCC 9.4.0]

Please report bugs in MSS to https://github.com/Open-MSS/MSS

Information about the fatal error:

Traceback (most recent call last):
  File "/home/reimar/PycharmProjects/2021/Jatin2020/MSS/mslib/msui/mscolab.py", line 277, in login_handler
    self.mscolab.after_login(emailid, self.mscolab_server_url, r)
  File "/home/reimar/PycharmProjects/2021/Jatin2020/MSS/mslib/msui/mscolab.py", line 520, in after_login
    self.add_operations_to_ui()
  File "/home/reimar/PycharmProjects/2021/Jatin2020/MSS/mslib/msui/mscolab.py", line 1200, in add_operations_to_ui
    _json = json.loads(r.text)
  File "/home/reimar/miniconda3/envs/mssdev/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/reimar/miniconda3/envs/mssdev/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/reimar/miniconda3/envs/mssdev/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by ReimarBauer** [comment]
occures when old server and new client is used
