### ISSUE TITLE
Sometimes BadNamespaceError on Operation Creation

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1314]
The operation was created successfully. Only the list got not updated. Toggling category refreshed the list.
```
CRITICAL: Fatal error: Traceback (most recent call last):
  File "/home/reimar/PycharmProjects/MSS/mslib/msui/mscolab.py", line 744, in add_operation
    self.conn.handle_new_operation(op_id)
  File "/home/reimar/PycharmProjects/MSS/mslib/msui/socket_control.py", line 144, in handle_new_operation
    self.sio.emit('add-user-to-operation', {
  File "/home/reimar/miniconda3/envs/mssdev/lib/python3.9/site-packages/socketio/client.py", line 384, in emit
    raise exceptions.BadNamespaceError(
socketio.exceptions.BadNamespaceError: / is not a connected namespace.
```

**Comment by ReimarBauer** [comment]
This is likly a network problem. We can look on improving this together with #1295

**Comment by ReimarBauer** [comment]
reopen when we have more details
