### ISSUE TITLE
some airspaces from openaip do not work

### ISSUE THREAD

**Issue by jgrooss** [Open-MSS/MSS#1324]
In MSS 6.0.0 the simultaneous display of multiple airspaces does not work.
In the case of selecting more European source files, it drops the following error message:

Fatal error in MSS 6.0.0. on Linux-5.11.0-43-generic-x86_64-with-glibc2.31
Python 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:46) 
[GCC 9.3.0]

Please report bugs in MSS to https://github.com/Open-MSS/MSS

Information about the fatal error:

Traceback (most recent call last):
  File "/home/icg122/anaconda3/envs/mssenv/lib/python3.9/site-packages/mslib/msui/airdata_dockwidget.py", line 77, in redraw_map
    self.view.map.set_draw_airspaces(self.cbDrawAirspaces.isChecked(), self.cbAirspaces.currentData(),
  File "/home/icg122/anaconda3/envs/mssenv/lib/python3.9/site-packages/mslib/msui/mpl_map.py", line 376, in set_draw_airspaces
    self.draw_airspaces(country_codes, range_km)
  File "/home/icg122/anaconda3/envs/mssenv/lib/python3.9/site-packages/mslib/msui/mpl_map.py", line 383, in draw_airspaces
    airspaces = copy.deepcopy(get_airspaces(countries))
  File "/home/icg122/anaconda3/envs/mssenv/lib/python3.9/site-packages/mslib/utils/airdata.py", line 183, in get_airspaces
    "top": float(elem.find("ALTLIMIT_TOP").find("ALT").text),
TypeError: float() argument must be a string or a number, not 'NoneType'

**Comment by ReimarBauer** [comment]
I can't reproduce, need more details.

![multiple_airspaces](https://user-images.githubusercontent.com/278728/148926482-d1cfb5e7-2986-4d4c-a308-b9beb169b771.gif)

Can you show which airspaces did not work ?

**Comment by ReimarBauer** [comment]
seems Estonia ee forces this traceback

**Comment by ReimarBauer** [comment]
The missing value for `<ALT UNIT="F"></ALT>` causes this traceback.
```
  <NAME>AREA G5 (NARVA)</NAME>
  <ALTLIMIT_TOP REFERENCE="">
    <ALT UNIT="F"></ALT>
  </ALTLIMIT_TOP>
```
