### ISSUE TITLE
crash on config save in section "import plugins"

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1331]
```

Fatal error in MSS 6.0.1. on Linux-5.4.0-94-generic-x86_64-with-glibc2.27
Python 3.9.9 | packaged by conda-forge | (main, Dec 20 2021, 02:41:03) 
[GCC 9.4.0]

Please report bugs in MSS to https://github.com/Open-MSS/MSS

Information about the fatal error:

Traceback (most recent call last):
  File "/home/reimar/miniconda3/envs/mssenv/lib/python3.9/site-packages/mslib/msui/mss_pyui.py", line 897, in restart_application
    self.remove_plugins()
  File "/home/reimar/miniconda3/envs/mssenv/lib/python3.9/site-packages/mslib/msui/mss_pyui.py", line 589, in remove_plugins
    for name, _ in self.import_plugins:
ValueError: too many values to unpack (expected 2)

```

**Comment by joernu76** [comment]
No crash for me. Insufficient information to reproduce. I assume that it depends on the contents of the config file...?

**Comment by ReimarBauer** [comment]
this was the initial configuration I ran in it
![my](https://user-images.githubusercontent.com/278728/149777338-a16255f2-8241-452e-a206-2db6e75be8c2.png)

I had it also with one Flitestar import plugin. 

With 6.0.2 it is solved
