### ISSUE TITLE
basemap version blocks py 3.10.0 build

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1337]
From the log of the pipeline https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=444392&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=841356e0-85bb-57d8-dbbc-852e683d1642&l=797

The reported errors are:
- Encountered problems while solving:
-   package basemap-1.2.2-py37hc66db60_2 requires proj, but none of the providers can be installed

**Comment by ReimarBauer** [comment]
there is a py310 basemap build available https://anaconda.org/conda-forge/basemap/files

and since a few day proj-9.0.0 as arch package https://anaconda.org/conda-forge/proj/files

**Comment by ReimarBauer** [comment]
```
The reported errors are:
- Encountered problems while solving:
-   - package basemap-1.3.2-py310hb079758_1 requires pyproj >=1.9.3,<3.4, but none of the providers can be installed
- 
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/boa/cli/mambabuild.py", line 124, in mamba_get_install_actions
    solution = solver.solve_for_action(_specs, prefix)
  File "/opt/conda/lib/python3.9/site-packages/boa/core/solver.py", line 234, in solve_for_action
    t = self.solve(specs)
  File "/opt/conda/lib/python3.9/site-packages/boa/core/solver.py", line 216, in solve
    raise RuntimeError("Solver could not find solution." + error_string)
RuntimeError: Solver could not find solution.Mamba failed to solve:
```

basemap-1.3.2-py310hb079758_1 comes von anaconda default, the conda-forge package is on 1.2.2 version.

**Comment by ReimarBauer** [comment]
related
https://github.com/conda-forge/basemap-feedstock/issues/87
