### ISSUE TITLE
on new operation  "/ is not a connected namespace" shown

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1356]
operation is created, seems only the communication fails.

```
CRITICAL: MSS Version: 6.0.2.
CRITICAL: Python Version: 3.9.9 | packaged by conda-forge | (main, Dec 20 2021, 02:41:03) 
[GCC 9.4.0]
CRITICAL: Platform: Linux-5.4.0-99-generic-x86_64-with-glibc2.27 (('64bit', 'ELF'))
CRITICAL: Fatal error: Traceback (most recent call last):
  File "/home/reimar/miniconda3/envs/mssenv/lib/python3.9/site-packages/mslib/msui/mscolab.py", line 742, in add_operation
    self.conn.handle_new_operation(op_id)
  File "/home/reimar/miniconda3/envs/mssenv/lib/python3.9/site-packages/mslib/msui/socket_control.py", line 144, in handle_new_operation
    self.sio.emit('add-user-to-operation', {
  File "/home/reimar/miniconda3/envs/mssenv/lib/python3.9/site-packages/socketio/client.py", line 393, in emit
    raise exceptions.BadNamespaceError(
socketio.exceptions.BadNamespaceError: / is not a connected namespace.

packet queue is empty, aborting
ERROR: packet queue is empty, aborting
packet queue is empty, aborting
ERROR: packet queue is empty, aborting
```

**Comment by ReimarBauer** [comment]
Hmm, error does not happen in my development environment with develop or stable.

**Comment by ReimarBauer** [comment]
This happen with flask-socketio    5.1.1  a downgrade to 5.1.0 solves this.

mamba install flask-socketio==5.1.0
