### ISSUE TITLE
some of the additional tools don't close completly

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#139]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/139) by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

```
#!python

System is loading..
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
Traceback (most recent call last):
  File "/home/mss/miniconda2/envs/mssdev/lib/python2.7/site-packages/mslib/msui/mss_pyui.py", line 438, in activateWindow
    item.window.showNormal()
RuntimeError: wrapped C/C++ object of type MSSTrajectoriesToolWindow has been deleted
Traceback (most recent call last):
  File "/home/mss/miniconda2/envs/mssdev/lib/python2.7/site-packages/mslib/msui/mss_pyui.py", line 438, in activateWindow
    item.window.showNormal()
RuntimeError: wrapped C/C++ object of type MSSTrajectoriesToolWindow has been deleted

```
![Bildschirmfoto von »2017-02-18 15-15-33«.png](https://bitbucket.org/repo/MBp6Xa/images/2544828414-Bildschirmfoto%20von%20%C2%BB2017-02-18%2015-15-33%C2%AB.png)

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

Trajectory Tool window now removes itself from the open-tool-list when closed.

Resolve issue #139
