### ISSUE TITLE
fatal error in mswms gallery on RTFD build

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1423]
seen this on the RTFD build of 6.0.6 

```
Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/mss/conda/stable/lib/python3.9/site-packages/sphinx/config.py", line 332, in eval_config_file
    exec(code, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/mss/checkouts/stable/docs/conf.py", line 67, in <module>
    mslib.mswms.wms.server.generate_gallery(sphinx=True, generate_code=True, all_plots=True, levels="3,4,200,300",
  File "/home/docs/checkouts/readthedocs.org/user_builds/mss/checkouts/stable/docs/../mslib/mswms/wms.py", line 244, in generate_gallery
    self.__init__()
  File "/home/docs/checkouts/readthedocs.org/user_builds/mss/checkouts/stable/docs/../mslib/mswms/wms.py", line 202, in __init__
    self.register_hsec_layer(datasets, layer)
  File "/home/docs/checkouts/readthedocs.org/user_builds/mss/checkouts/stable/docs/../mslib/mswms/wms.py", line 456, in register_hsec_layer
    raise ValueError(f"new layer is already registered? dataset={dataset} layer.name={layer.name} "
ValueError: new layer is already registered? dataset=ecmwf_EUR_LL015 layer.name=BASEMAP new=<mslib.mswms.mpl_hsec.MPLBasemapHorizontalSectionStyle object at 0x7f6ffa2921c0> old=<mslib.mswms.mpl_hsec_styles.HS_GenericStyle object at 0x7f6ffa2a92e0>
```

This can locally reproduced by MSS/docs$ make html

**Comment by ReimarBauer** [comment]
```
 cftime.DatetimeGregorian(2012, 10, 19, 0, 0, 0, 0, has_year_zero=False)]' standard_names='['lagrangian_tendency_of_air_pressure']'
2022-04-14 12:19:20 register_hsec_layer || registering horizontal section layer 'BLH' with dataset 'ecmwf_EUR_LL015'
2022-04-14 12:19:20 register_hsec_layer || registering horizontal section layer 'TCC' with dataset 'ecmwf_EUR_LL015'
2022-04-14 12:19:20 register_hsec_layer || registering horizontal section layer 'PLDiv01' with dataset 'ecmwf_EUR_LL015'
2022-04-14 12:19:20 register_hsec_layer || registering horizontal section layer 'EMAC_Eyja_Tracer' with dataset 'ecmwf_EUR_LL015'
2022-04-14 12:19:20 register_hsec_layer || registering horizontal section layer 'EMAC_Eyja_TotalColumn' with dataset 'ecmwf_EUR_LL015'
2022-04-14 12:19:20 register_hsec_layer || registering horizontal section layer 'PLEQPT01' with dataset 'ecmwf_EUR_LL015'
2022-04-14 12:19:20 register_hsec_layer || registering horizontal section layer 'BASEMAP' with dataset 'ecmwf_EUR_LL015'
2022-04-14 12:19:20 register_hsec_layer || registering horizontal section layer 'PLGeopWind' with dataset 'ecmwf_EUR_LL015'
2022-04-14 12:19:20 register_hsec_layer || registering horizontal section layer 'PLLagrantoTraj' with dataset 'ecmwf_EUR_LL015'
2022-04-14 12:19:20 register_hsec_layer || registering horizontal section layer 'MSLP' with dataset 'ecmwf_EUR_LL015'
2022-04-14 12:19:20 register_hsec_layer || registering horizontal section layer 'MSG_BT108' with dataset 'ecmwf_EUR_LL015'
2022-04-14 12:19:20 register_hsec_layer || registering horizontal section layer 'PVTropo01' with dataset 'ecmwf_EUR_LL015'
2022-04-14 12:19:20 register_hsec_layer || registering horizontal section layer 'PLRelHum01' with dataset 'ecmwf_EUR_LL015'
2022-04-14 12:19:20 register_hsec_layer || registering horizontal section layer 'SEA' with dataset 'ecmwf_EUR_LL015'
2022-04-14 12:19:20 register_hsec_layer || registering horizontal section layer 'CI' with dataset 'ecmwf_EUR_LL015'
2022-04-14 12:19:20 register_hsec_layer || registering horizontal section layer 'MLTemp01' with dataset 'ecmwf_EUR_LL015'
2022-04-14 12:19:20 register_hsec_layer || registering horizontal section layer 'PLTemp01' with dataset 'ecmwf_EUR_LL015'
2022-04-14 12:19:20 register_hsec_layer || registering horizontal section layer 'ThermalTropo01' with dataset 'ecmwf_EUR_LL015'
2022-04-14 12:19:20 register_hsec_layer || registering horizontal section layer 'VIProbWCB' with dataset 'ecmwf_EUR_LL015'
2022-04-14 12:19:20 register_hsec_layer || registering horizontal section layer 'PLW01' with dataset 'ecmwf_EUR_LL015'
2022-04-14 12:19:20 register_hsec_layer || registering horizontal section layer 'BASEMAP' with dataset 'ecmwf_EUR_LL015'

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/reimar/miniconda3/envs/mssdev/lib/python3.9/site-packages/sphinx/config.py", line 340, in eval_config_file
    exec(code, namespace)
  File "/home/reimar/MASTER/MSS/docs/conf.py", line 67, in <module>
    mslib.mswms.wms.server.generate_gallery(sphinx=True, generate_code=True, all_plots=True, levels="3,4,200,300",
  File "/home/reimar/MASTER/MSS/docs/../mslib/mswms/wms.py", line 244, in generate_gallery
    self.__init__()
  File "/home/reimar/MASTER/MSS/docs/../mslib/mswms/wms.py", line 202, in __init__
    self.register_hsec_layer(datasets, layer)
  File "/home/reimar/MASTER/MSS/docs/../mslib/mswms/wms.py", line 456, in register_hsec_layer
    raise ValueError(f"new layer is already registered? dataset={dataset} layer.name={layer.name} "
ValueError: new layer is already registered? dataset=ecmwf_EUR_LL015 layer.name=BASEMAP new=<mslib.mswms.mpl_hsec.MPLBasemapHorizontalSectionStyle object at 0x7f9d91e501c0> old=<mslib.mswms.mpl_hsec_styles.HS_GenericStyle object at 0x7f9d91e6e670>

Makefile:58: recipe for target 'html' failed
make: *** [html] Error 2
```
