### ISSUE TITLE
python 3.10 build is blocked by some fixations

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1440]
A build of MSS for python 3.10 fails because of our fixation of geos
We pinned it to geos <3.9.0

```
The reported errors are:
- Encountered problems while solving:
-   - package basemap-1.2.2-py310hfa8993b_4 requires geos >=3.9.1,<3.9.2.0a0, but none of the providers can be installed
- 
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/boa/cli/mambabuild.py", line 124, in mamba_get_install_actions
    solution = solver.solve_for_action(_specs, prefix)
  File "/opt/conda/lib/python3.9/site-packages/boa/core/solver.py", line 226, in solve_for_action
    t = self.solve(specs)
  File "/opt/conda/lib/python3.9/site-packages/boa/core/solver.py", line 216, in solve
    raise RuntimeError("Solver could not find solution." + error_string)
RuntimeError: Solver could not find solution.Mamba failed to solve

```

**Comment by ReimarBauer** [comment]
I forced geos==3.9.1 and all tests succeed,

```
mamba list geos
# packages in environment at /home/reimar/miniconda3/envs/mssdev:
#
# Name                    Version                   Build  Channel
geos                      3.9.1                h9c3ff4c_2    conda-forge
(mssdev) reimar@infinte:~/PycharmProjects/MSS$ 
```

https://github.com/Open-MSS/MSS/issues/665

**Comment by ReimarBauer** [comment]
solution is likly to remove geos from our build meta.yaml

**Comment by ReimarBauer** [comment]
removing geos gets me a step further,  now we have a qt problem. 
https://github.com/conda-forge/mss-feedstock/pull/119

**Comment by ReimarBauer** [comment]
geos 3.9.x has a problem. May be we can help to find a solution?

https://github.com/matplotlib/basemap/issues/522

**Comment by ReimarBauer** [comment]
We retry with develop and basemap-1.3.3
https://github.com/conda-forge/basemap-feedstock/pull/96

**Comment by ReimarBauer** [comment]
hints for updating basemap https://github.com/matplotlib/basemap/blob/v1.3.3/CHANGELOG.md#changed-3

**Comment by ReimarBauer** [comment]
I've tested the configuration by a PR on C-F and will add this next for a 6.2.0 release
https://github.com/conda-forge/mss-feedstock/pull/119

We should verify some geos problems if they are solved

**Comment by ReimarBauer** [comment]
If this still exists we may try solve this
https://github.com/matplotlib/basemap/issues/522
