### ISSUE TITLE
Help - Search has problems on closed views

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1476]
When we close a view the search elements don't get updated and calling it again gives a traceback

![close_window](https://user-images.githubusercontent.com/278728/172470655-defc424d-2045-4b1d-b9c6-932bb86c0cc6.gif)

```
Fatal error in MSS 6.2.1. on Linux-5.4.0-113-generic-x86_64-with-glibc2.27
Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:56:21) 
[GCC 10.3.0]

Please report bugs in MSS to https://github.com/Open-MSS/MSS

Information about the fatal error:

Traceback (most recent call last):
  File "/home/reimar/miniconda3/envs/newyenv/lib/python3.9/site-packages/mslib/msui/msui.py", line 387, in <lambda>
    self.actionSearch.triggered.connect(lambda: self.show_shortcuts(True))
  File "/home/reimar/miniconda3/envs/newyenv/lib/python3.9/site-packages/mslib/msui/msui.py", line 927, in show_shortcuts
    self.shortcuts_dlg.fill_list()
  File "/home/reimar/miniconda3/envs/newyenv/lib/python3.9/site-packages/mslib/msui/msui.py", line 216, in fill_list
    self.reset_highlight()
  File "/home/reimar/miniconda3/envs/newyenv/lib/python3.9/site-packages/mslib/msui/msui.py", line 183, in reset_highlight
    shortcut[-1].setStyleSheet("")
RuntimeError: wrapped C/C++ object of type QPushButton has been deleted

```

**Comment by ReimarBauer** [comment]
Also the inactive elemets are visible. e.g. chat should only be shown when a server is connected and a user logged in and has the role to use a chat.
