### ISSUE TITLE
kml overlay does not change  color in python 3.10.x

### ISSUE THREAD

**Issue by jgrooss** [Open-MSS/MSS#1500]
kml overlay problem

When trying to change the color of an kml overlay in the top view, I get the following error:
```
Fatal error in MSS 7.0.0. on Linux-5.13.0-40-generic-x86_64-with-glibc2.31
Python 3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:04:59) [GCC 10.3.0]

Please report bugs in MSS to https://github.com/Open-MSS/MSS

Information about the fatal error:

Traceback (most recent call last):
  File "/private/icg122/software/anaconda3/envs/mssenv/lib/python3.10/site-packages/mslib/msui/kmloverlay_dockwidget.py", line 374, in select_color
    self.listWidget.currentItem().setIcon(self.show_color_icon(filename, self.set_color(filename)))
  File "/private/icg122/software/anaconda3/envs/mssenv/lib/python3.10/site-packages/mslib/msui/kmloverlay_dockwidget.py", line 433, in show_color_icon
    pixmap.fill(QtGui.QColor(clr[0] * 255, clr[1] * 255, clr[2] * 255))
TypeError: arguments did not match any overloaded call:
  QColor(Qt.GlobalColor): argument 1 has unexpected type 'float'
  QColor(int): argument 1 has unexpected type 'float'
  QColor(QRgba64): argument 1 has unexpected type 'float'
  QColor(Any): too many arguments
  QColor(): too many arguments
  QColor(int, int, int, alpha: int = 255): argument 1 has unexpected type 'float'
  QColor(str): argument 1 has unexpected type 'float'
  QColor(Union[QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'
```

**Comment by jgrooss** [comment]
This is the kml file
[fir_acclip.kml.txt](https://github.com/Open-MSS/MSS/files/9028905/fir_acclip.kml.txt)
 (rename to *.kml)

**Comment by ReimarBauer** [comment]
checked in my developer environment python 3.9.13 with the tutorials. They and also the tests don't see this. 

https://user-images.githubusercontent.com/278728/176935030-b25177b4-49b1-4024-a4d6-50f066d07b6d.mp4
