### ISSUE TITLE
mss kml color change crashes on stable

### ISSUE THREAD

**Issue by joernu76** [Open-MSS/MSS#1526]
Error message
```
Traceback (most recent call last):
  File "/opt/anaconda3/envs/mss-7.0.0/lib/python3.10/site-packages/mslib/msui/kmloverlay_dockwidget.py", line 397, in select_linewidth
    self.listWidget.currentItem().setIcon(self.show_color_icon(filename, self.set_color(filename)))
  File "/opt/anaconda3/envs/mss-7.0.0/lib/python3.10/site-packages/mslib/msui/kmloverlay_dockwidget.py", line 433, in show_color_icon
    pixmap.fill(QtGui.QColor(clr[0] * 255, clr[1] * 255, clr[2] * 255))
TypeError: arguments did not match any overloaded call:
  QColor(Qt.GlobalColor): argument 1 has unexpected type 'float'
  QColor(int): argument 1 has unexpected type 'float'
  QColor(QRgba64): argument 1 has unexpected type 'float'
  QColor(Any): too many arguments
  QColor(): too many arguments
  QColor(int, int, int, alpha: int = 255): argument 1 has unexpected type 'float'
  QColor(str): argument 1 has unexpected type 'float'
  QColor(Union[QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'
```

**Comment by ReimarBauer** [comment]
This is a duplicate of #1500 and is fixed in 7.0.1

**Comment by ReimarBauer** [comment]
https://github.com/Open-MSS/MSS/pull/1501

**Comment by ReimarBauer** [comment]
please update to 7.0.2

**Comment by ReimarBauer** [comment]
and btw. this is an uncommon installation, because mss was not installed into an env.

https://conda.io/projects/conda/en/latest/user-guide/getting-started.html#managing-environments
When you begin using conda, you already have a default environment named `base`. **You don't want to put programs into your base environment, though.**  Create separate environments to keep your programs isolated from each other.

**Comment by joernu76** [comment]
Was indeed fixed.
