### ISSUE TITLE
fatal error by "No" for WARNING: Selected CRS 'EPSG:77740010' not contained in allowed list of supported CRS for this WMS

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1535]
![no_gives_a_traceback](https://user-images.githubusercontent.com/278728/186234748-8fb4a4fd-8019-40c2-9361-7f556420f1e3.png)

```
Fatal error in MSS 7.0.2. on Linux-5.4.0-124-generic-x86_64-with-glibc2.27
Python 3.10.4 | packaged by conda-forge | (main, Mar 24 2022, 17:38:57) [GCC 10.3.0]

Please report bugs in MSS to https://github.com/Open-MSS/MSS

Information about the fatal error:

Traceback (most recent call last):
  File "/home/reimar/miniconda3/envs/mssenv/lib/python3.10/site-packages/mslib/msui/wms_control.py", line 1377, in after_redraw
    self.auto_update()
  File "/home/reimar/miniconda3/envs/mssenv/lib/python3.10/site-packages/mslib/msui/wms_control.py", line 1031, in auto_update
    self.get_all_maps()
  File "/home/reimar/miniconda3/envs/mssenv/lib/python3.10/site-packages/mslib/msui/wms_control.py", line 550, in get_all_maps
    self.get_map([self.multilayers.get_current_layer()])
  File "/home/reimar/miniconda3/envs/mssenv/lib/python3.10/site-packages/mslib/msui/wms_control.py", line 1603, in get_map
    args.extend(self.retrieve_image(layer, crs, bbox_tmp, None, width, height, transparent))
TypeError: 'NoneType' object is not iterable
```

**Comment by ReimarBauer** [comment]
not reproducable in recent stable. Needs more details when we find this again.
