### ISSUE TITLE
review apps.ecmwf.int/wms/ example wms servers

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1539]
this seems offline https://eumetview.eumetsat.int/geoserver/wms

**Comment by ReimarBauer** [comment]
https://apps.ecmwf.int/wms/?token=public

and accessing Pm2.5 anthro....
```
ERROR:
<class 'owslib.util.ServiceException'>
Data not found [{u'base_time': datetime.datetime(2000, 1, 1, 0, 0), u'stream': u'oper', u'package': u'cams_air_quality_forecast', u'levtype': u'sfc', u'param': u'15.216', u'step': 0, u'expver': u'5001', u'time': None, u'type': u'fc', u'class': u'mc'}]

Traceback (most recent call last):
  File "./eccharts/wms/views.py", line 204, in wrapper
    return wrapped(*args)
  File "./eccharts/wms/views.py", line 477, in wms
    return getmap(request)
  File "./common/soa/utils.py", line 66, in cache_headers_from_service
    response, result = wrapped(*args, **kwargs)
  File "./eccharts/wms/views.py", line 869, in getmap
    if isinstance(graph_res.result, list):
  File "/data/webdev/lib/servicelib/client.py", line 292, in result
    r, _ = self.wait(self.timeout)
  File "/data/webdev/lib/servicelib/client.py", line 270, in wait
    raise errors.Serializable.from_dict(result)
Serializable: Data not found [{u'base_time': datetime.datetime(2000, 1, 1, 0, 0), u'stream': u'oper', u'package': u'cams_air_quality_forecast', u'levtype': u'sfc', u'param': u'15.216', u'step': 0, u'expver': u'5001', u'time': None, u'type': u'fc', u'class': u'mc'}]
```

**Comment by ReimarBauer** [comment]
We see here the reaction of the external server on an owslib request. Seems we can't use the provided data at the moment.
