### ISSUE TITLE
Failed to pyproj from mpl_toolkits.basemap and updater problem in docker container (and icon start)

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1540]
`docker run   --net=host -ti --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix/:/tmp/.X11-unix openmss/mss MSS`

```
2022-08-29 17:57:32 register_lsec_layer || registering linear section layer 'LS_RH01' with dataset 'ecmwf_EUR_LL015'
2022-08-29 17:57:32 register_lsec_layer || registering linear section layer 'LS_HV01' with dataset 'ecmwf_EUR_LL015'
2022-08-29 17:57:32 register_lsec_layer || registering linear section layer 'LS_W01' with dataset 'ecmwf_EUR_LL015'
2022-08-29 17:57:32            <module> || Failed to pyproj from mpl_toolkits.basemap
Traceback (most recent call last):
  File "/opt/conda/envs/mssenv/bin/mswms", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/envs/mssenv/lib/python3.9/site-packages/mslib/mswms/mswms.py", line 89, in main
    updater = Updater()
  File "/opt/conda/envs/mssenv/lib/python3.9/site-packages/mslib/utils/qt.py", line 451, in __init__
    self.command = os.path.join(self.conda_prefix, 'bin', "conda")
  File "/opt/conda/envs/mssenv/lib/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
2022-08-29 17:57:32          excepthook || MSS Version: 7.0.3.
2022-08-29 17:57:32          excepthook || Python Version: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:56:21) 
[GCC 10.3.0]
2022-08-29 17:57:32          excepthook || Platform: Linux-5.4.0-124-generic-x86_64-with-glibc2.31 (('64bit', 'ELF'))
2022-08-29 17:57:32          excepthook || Fatal error: Traceback (most recent call last):
  File "/opt/conda/envs/mssenv/bin/mswms", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/envs/mssenv/lib/python3.9/site-packages/mslib/mswms/mswms.py", line 89, in main
    updater = Updater()
  File "/opt/conda/envs/mssenv/lib/python3.9/site-packages/mslib/utils/qt.py", line 451, in __init__
    self.command = os.path.join(self.conda_prefix, 'bin', "conda")
  File "/opt/conda/envs/mssenv/lib/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

QWidget: Must construct a QApplication before a QWidget
/scripts/script.sh: line 20:    14 Aborted                 mswms gallery --create
```

**Comment by ReimarBauer** [comment]
a manual start did also see the pyproj failure but did not stop

` docker run   --net=host -ti --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix/:/tmp/.X11-unix openmss/mss /bin/bash`
```
conda activate mssenv
mswms_demodata --seed
export PYTHONPATH=~/mss
mswms
```
shows

```
2022-08-29 18:11:15 register_lsec_layer || registering linear section layer 'LS_RH01' with dataset 'ecmwf_EUR_LL015'
2022-08-29 18:11:15 register_lsec_layer || registering linear section layer 'LS_HV01' with dataset 'ecmwf_EUR_LL015'
2022-08-29 18:11:15 register_lsec_layer || registering linear section layer 'LS_W01' with dataset 'ecmwf_EUR_LL015'
2022-08-29 18:11:15            <module> || Failed to pyproj from mpl_toolkits.basemap
INFO: Configuration File: '/root/mss/mswms_settings.py'
 * Serving Flask app 'mslib.mswms.wms' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
INFO: WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:8081
INFO: Press CTRL+C to quit
```

**Comment by ReimarBauer** [comment]
The problem comes from the recent updater improvement. We have to ommit a docker container setup

**Comment by ReimarBauer** [comment]
The traceback is addressed on 
https://github.com/Open-MSS/MSS/issues/1541

this needs to become tracked down, likly independent from docker
2022-08-29 18:11:15            <module> || Failed to pyproj from mpl_toolkits.basemap

**Comment by ReimarBauer** [comment]
In the docker container we likly can bypass how entry points are used but in general also entry points should start the environment, see
https://github.com/conda/conda/issues/11787

**Comment by ReimarBauer** [comment]
with 7.0.5 docker image, both servers and client start.
```
$ xhost +local:docker
$  docker run -d --net=host -ti --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix/:/tmp/.X11-unix openmss/mss:latest MSS
```

**Comment by ReimarBauer** [comment]
https://github.com/Open-MSS/dockerhub/issues/46
