### ISSUE TITLE
The updater should not crash in a docker container or on start without an environment (linux msui icon on program manager)

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1541]
`docker run   --net=host -ti --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix/:/tmp/.X11-unix openmss/mss MSS`

```
Traceback (most recent call last):
  File "/opt/conda/envs/mssenv/bin/mswms", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/envs/mssenv/lib/python3.9/site-packages/mslib/mswms/mswms.py", line 89, in main
    updater = Updater()
  File "/opt/conda/envs/mssenv/lib/python3.9/site-packages/mslib/utils/qt.py", line 451, in __init__
    self.command = os.path.join(self.conda_prefix, 'bin', "conda")
  File "/opt/conda/envs/mssenv/lib/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
2022-08-29 18:21:03          excepthook || MSS Version: 7.0.3.
2022-08-29 18:21:03          excepthook || Python Version: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:56:21) 
[GCC 10.3.0]
2022-08-29 18:21:03          excepthook || Platform: Linux-5.4.0-124-generic-x86_64-with-glibc2.31 (('64bit', 'ELF'))
2022-08-29 18:21:03          excepthook || Fatal error: Traceback (most recent call last):
  File "/opt/conda/envs/mssenv/bin/mswms", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/envs/mssenv/lib/python3.9/site-packages/mslib/mswms/mswms.py", line 89, in main
    updater = Updater()
  File "/opt/conda/envs/mssenv/lib/python3.9/site-packages/mslib/utils/qt.py", line 451, in __init__
    self.command = os.path.join(self.conda_prefix, 'bin', "conda")
  File "/opt/conda/envs/mssenv/lib/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

The problem was introduced by https://github.com/Open-MSS/MSS/pull/1513/files#diff-5c39c5f9af4c2325fd21b9d539f813296d580fb6b67b960340a4bb8a9b1e6fbeR451

os.getenv("CONDA_PREFIX") seems to be None in the docker container and also when we start msui by the icon.

in case of None we should fall back to the conda command.

**Comment by ReimarBauer** [comment]
since https://github.com/Open-MSS/MSS/releases/tag/7.0.2

**Comment by ReimarBauer** [comment]
On windows it is different implemented. There it starts, after 20 seconds on that small machine.

![windows_works](https://user-images.githubusercontent.com/278728/188385286-4bbb698b-bd3c-48dd-a81f-ee71a3a3ce48.gif)
