### ISSUE TITLE
mscolab manage_user add a user in a role problem

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1556]
When a creator invites someone using manage users there is sometimes a traceback created

**Comment by ReimarBauer** [comment]
```
Fatal error in MSS 7.0.4. on Linux-5.4.0-125-generic-x86_64-with-glibc2.27
Python 3.10.4 | packaged by conda-forge | (main, Mar 24 2022, 17:38:57) [GCC 10.3.0]

Please report bugs in MSS to https://github.com/Open-MSS/MSS

Information about the fatal error:

Traceback (most recent call last):
  File "/home/reimar/miniconda3/envs/mssdev/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/reimar/miniconda3/envs/mssdev/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/reimar/miniconda3/envs/mssdev/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/reimar/miniconda3/envs/mssdev/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/reimar/PycharmProjects/MSS/mslib/msui/mscolab_admin_window.py", line 256, in add_selected_users
    res = res.json()
  File "/home/reimar/miniconda3/envs/mssdev/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
