### ISSUE TITLE
tutorials find some problem in wms_control

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1653]
recently with the tutorial_views.py I am catching some networking problems.

It starts with:

![networking_problem](https://user-images.githubusercontent.com/278728/211337151-30a5998e-c77f-4f63-8ad1-3f1176a754f1.png)

checking manually the GetCapabilities request by a browser did not find a problem.
continuing on the UI shows

```
Fatal error in MSS 7.0.7. on Linux-5.4.0-136-generic-x86_64-with-glibc2.27
Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:58:50) 
[GCC 10.3.0]

Please report bugs in MSS to https://github.com/Open-MSS/MSS

Information about the fatal error:

Traceback (most recent call last):
  File "/home/reimar/PycharmProjects/MSS/mslib/msui/wms_control.py", line 595, in on_success
    self.activate_wms(wms)
  File "/home/reimar/PycharmProjects/MSS/mslib/msui/wms_control.py", line 763, in activate_wms
    self.prefetch.disconnect(self.prefetcher.fetch_maps)
TypeError: disconnect() failed between 'prefetch' and 'fetch_maps'
```
removing and adding the server did not make a change.

Also changing to another server, e.g.  https://eumetview.eumetsat.int/geoserver/wms  shows the same problem

**Comment by ReimarBauer** [comment]
the host is wrong. This needs more informations.
