### ISSUE TITLE
sattelite prediction without filename crashes

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1706]
![sattelite_prediction_without_file](https://user-images.githubusercontent.com/278728/226323123-f04445a0-1687-4d5d-bdfe-439effc3dc45.gif)

```
CRITICAL: Fatal error: Traceback (most recent call last):
  File "/home/reimar/PycharmProjects/MSS/mslib/msui/satellite_dockwidget.py", line 155, in load_file
    overpass_segments = read_nasa_satellite_prediction(filename)
  File "/home/reimar/PycharmProjects/MSS/mslib/msui/satellite_dockwidget.py", line 64, in read_nasa_satellite_prediction
    satfile = _fs.open(_name, 'r')
  File "/home/reimar/miniconda3/envs/mssdev/lib/python3.9/site-packages/fs/osfs.py", line 642, in open
    raise FileExpected(path)
fs.errors.FileExpected: path '' should be a file
```

**Comment by ReimarBauer** [comment]
"load" button may be only active when a file was selected

and also a failure message could be shown as popup on the exception
