### ISSUE TITLE
msui login to mscolab did not find keyring backend in docker image

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1743]
```
Fatal error in MSS 8.0.0 on Linux-5.4.0-147-generic-x86_64-with-glibc2.31
Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:56:21) 
[GCC 10.3.0]

Please report bugs in MSS to https://github.com/Open-MSS/MSS

Information about the fatal error:

Traceback (most recent call last):
  File "/opt/conda/envs/mssenv/lib/python3.9/site-packages/mslib/msui/mscolab.py", line 354, in new_user_handler
    self.save_user_credentials_to_config_file(emailid, password)
  File "/opt/conda/envs/mssenv/lib/python3.9/site-packages/mslib/msui/mscolab.py", line 287, in save_user_credentials_to_config_file
    save_password_to_keyring(service_name="MSCOLAB", username=emailid, password=password)
  File "/opt/conda/envs/mssenv/lib/python3.9/site-packages/mslib/utils/auth.py", line 75, in save_password_to_keyring
    keyring.set_password(service_name=service_name, username=username, password=password)
  File "/opt/conda/envs/mssenv/lib/python3.9/site-packages/keyring/core.py", line 60, in set_password
    get_keyring().set_password(service_name, username, password)
  File "/opt/conda/envs/mssenv/lib/python3.9/site-packages/keyring/backends/fail.py", line 25, in get_password
    raise NoKeyringError(msg)
keyring.errors.NoKeyringError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.
```

**Comment by ReimarBauer** [comment]
similar problem on login

```
Fatal error in MSS 8.0.0 on Linux-5.4.0-147-generic-x86_64-with-glibc2.31
Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:56:21) 
[GCC 10.3.0]

Please report bugs in MSS to https://github.com/Open-MSS/MSS

Information about the fatal error:

Traceback (most recent call last):
  File "/opt/conda/envs/mssenv/lib/python3.9/site-packages/mslib/msui/mscolab.py", line 279, in login_handler
    save_password_to_keyring(service_name="MSCOLAB", username=emailid, password=password)
  File "/opt/conda/envs/mssenv/lib/python3.9/site-packages/mslib/utils/auth.py", line 75, in save_password_to_keyring
    keyring.set_password(service_name=service_name, username=username, password=password)
  File "/opt/conda/envs/mssenv/lib/python3.9/site-packages/keyring/core.py", line 60, in set_password
    get_keyring().set_password(service_name, username, password)
  File "/opt/conda/envs/mssenv/lib/python3.9/site-packages/keyring/backends/fail.py", line 25, in get_password
    raise NoKeyringError(msg)
keyring.errors.NoKeyringError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.
```

**Comment by ReimarBauer** [comment]
When we have keyring.errors.NoKeyringError we should just not use that, login and user creation should not crash. just less comfort.

**Comment by ReimarBauer** [comment]
we xould also look if someone got that working for headless
https://github.com/jaraco/keyring/pull/505/files

**Comment by ReimarBauer** [comment]
This needs also an exception handling
```
CRITICAL: Platform: Linux-5.4.0-147-generic-x86_64-with-glibc2.31 (('64bit', 'ELF'))
CRITICAL: Fatal error: Traceback (most recent call last):
  File "/opt/conda/envs/mssenv/lib/python3.9/site-packages/secretstorage/util.py", line 48, in send_and_get_reply
    raise DBusErrorResponse(resp_msg)
jeepney.wrappers.DBusErrorResponse: [org.freedesktop.DBus.Error.Spawn.ExecFailed] ('Failed to execute program org.freedesktop.secrets: Operation not permitted',)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/mssenv/lib/python3.9/site-packages/keyring/backends/SecretService.py", line 61, in get_preferred_collection
    collection = secretstorage.get_default_collection(bus)
  File "/opt/conda/envs/mssenv/lib/python3.9/site-packages/secretstorage/collection.py", line 177, in get_default_collection
    return Collection(connection)
  File "/opt/conda/envs/mssenv/lib/python3.9/site-packages/secretstorage/collection.py", line 45, in __init__
    self._collection.get_property('Label')
  File "/opt/conda/envs/mssenv/lib/python3.9/site-packages/secretstorage/util.py", line 67, in get_property
    (signature, value), = self.send_and_get_reply(msg)
  File "/opt/conda/envs/mssenv/lib/python3.9/site-packages/secretstorage/util.py", line 58, in send_and_get_reply
    raise SecretServiceNotAvailableException(data) from resp
secretstorage.exceptions.SecretServiceNotAvailableException: Failed to execute program org.freedesktop.secrets: Operation not permitted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/mssenv/lib/python3.9/site-packages/mslib/msui/mscolab.py", line 279, in login_handler
    save_password_to_keyring(service_name="MSCOLAB", username=emailid, password=password)
  File "/opt/conda/envs/mssenv/lib/python3.9/site-packages/mslib/utils/auth.py", line 76, in save_password_to_keyring
    keyring.set_password(service_name=service_name, username=username, password=password)
  File "/opt/conda/envs/mssenv/lib/python3.9/site-packages/keyring/core.py", line 60, in set_password
    get_keyring().set_password(service_name, username, password)
  File "/opt/conda/envs/mssenv/lib/python3.9/site-packages/keyring/backends/SecretService.py", line 87, in set_password
    collection = self.get_preferred_collection()
  File "/opt/conda/envs/mssenv/lib/python3.9/site-packages/keyring/backends/SecretService.py", line 63, in get_preferred_collection
    raise InitError("Failed to create the collection: %s." % e)
keyring.errors.InitError: Failed to create the collection: Failed to execute program org.freedesktop.secrets: Operation not permitted.
```

**Comment by ReimarBauer** [comment]
```
Traceback (most recent call last):
  File "/opt/conda/envs/mssenv/lib/python3.9/site-packages/mslib/msui/mscolab.py", line 310, in login_server_auth
    self.save_auth_credentials_to_config_file()
  File "/opt/conda/envs/mssenv/lib/python3.9/site-packages/mslib/msui/mscolab.py", line 387, in save_auth_credentials_to_config_file
    save_password_to_keyring(self.mscolab_server_url, auth_username, auth_password)
  File "/opt/conda/envs/mssenv/lib/python3.9/site-packages/mslib/utils/auth.py", line 76, in save_password_to_keyring
    keyring.set_password(service_name=service_name, username=username, password=password)
  File "/opt/conda/envs/mssenv/lib/python3.9/site-packages/keyring/core.py", line 60, in set_password
    get_keyring().set_password(service_name, username, password)
  File "/opt/conda/envs/mssenv/lib/python3.9/site-packages/keyring/backends/SecretService.py", line 87, in set_password
    collection = self.get_preferred_collection()
  File "/opt/conda/envs/mssenv/lib/python3.9/site-packages/keyring/backends/SecretService.py", line 63, in get_preferred_collection
    raise InitError("Failed to create the collection: %s." % e)
keyring.errors.InitError: Failed to create the collection: Failed to execute program org.freedesktop.secrets: Operation not permitted.
```
