### ISSUE TITLE
ImportError: on  python ./mss_pyui.py

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#177]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/177) by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

We have a missing module which gives this error
```
#!python

 python ./mss_pyui.py
Traceback (most recent call last):
  File "./mss_pyui.py", line 46, in <module>
    from mslib.msui.mss_qt import ui_mainwindow as ui
ImportError: cannot import name ui_mainwindow

```

**Comment by ReimarBauer** [comment]
**Original comment by Joern Ungermann (Bitbucket: [joernu76](https://bitbucket.org/joernu76), GitHub: [joernu76](https://github.com/joernu76)).**

----------------------------------------

The module in question is present and it works on my end for both PyQT4 and PyQt5.
But there may be a timing thing with the order of how the modules are imported and executed.
Can you provide instructions how to reproduce the error? Does this relate to the anaconda installed package or the development in the git repo?

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

everything works using pycharm or the conda installed program but that has also worked some time ago




```
#!python

/msui$ python ./mss_pyui.py
WARNING:nappy.nappy_api:You cannot use nappy NetCDF conversion tools as your system does not have CDMS installed, or it is not in your sys.path.
Traceback (most recent call last):
  File "./mss_pyui.py", line 57, in <module>
    from mslib.utils import config_loader, setup_logging
ImportError: cannot import name setup_logging
CRITICAL:root:Fatal error: Traceback (most recent call last):
  File "./mss_pyui.py", line 57, in <module>
    from mslib.utils import config_loader, setup_logging
ImportError: cannot import name setup_logging

QWidget: Must construct a QApplication before a QPaintDevice
Abgebrochen (Speicherabzug geschrieben)
```

**Comment by ReimarBauer** [comment]
**Original comment by Joern Ungermann (Bitbucket: [joernu76](https://bitbucket.org/joernu76), GitHub: [joernu76](https://github.com/joernu76)).**

----------------------------------------

Is this the same or a related error?
I also miss a more concrete description of how to replicate the error. 

For the example above, it is not even clear, what mslib is found by mss_pyui as the local one shouldnt be.

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

it is the same poblem. But it is only a kind of develoment issue. 

I can ran py.test from my terminal using the env and that is able to do all tests.

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

seems to got solved by one of the other commits before.



```
#!python

~/projects/mss/mslib/msui$ python ./mss_pyui.py
WARNING:nappy.nappy_api:You cannot use nappy NetCDF conversion tools as your system does not have CDMS installed, or it is not in your sys.path.
INFO: Launching user interface...
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
```

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

reopen if it happens again
