### ISSUE TITLE
Error on start of msui related to pint and units

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1777]
```
(mssenv) PS C:\WINDOWS\system32> msui
Traceback (most recent call last):
  File "C:\Users\Iam\miniconda3\envs\mssenv\Scripts\msui-script.py", line 6, in <module>
    from mslib.msui.msui import main
  File "C:\Users\Iam\miniconda3\envs\mssenv\lib\site-packages\mslib\msui\msui.py", line 68, in <module>
    from mslib.utils.qt import ui_mainwindow as ui
  File "C:\Users\Iam\miniconda3\envs\mssenv\lib\site-packages\mslib\utils\qt.py", line 640, in <module>
    globals()[mod] = importlib.import_module("mslib.msui.qt5." + mod)
  File "C:\Users\Iam\miniconda3\envs\mssenv\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Iam\miniconda3\envs\mssenv\lib\site-packages\mslib\msui\qt5\ui_sideview_window.py", line 66, in <module>
    from mslib.msui.mpl_qtwidget import MplSideViewWidget
  File "C:\Users\Iam\miniconda3\envs\mssenv\lib\site-packages\mslib\msui\mpl_qtwidget.py", line 46, in <module>
    from mslib.utils.thermolib import convert_pressure_to_vertical_axis_measure
  File "C:\Users\Iam\miniconda3\envs\mssenv\lib\site-packages\mslib\utils\thermolib.py", line 31, in <module>
    from mslib.utils.units import units, check_units
  File "C:\Users\Iam\miniconda3\envs\mssenv\lib\site-packages\mslib\utils\units.py", line 44, in <module>
    units.define("ppm = 1e-6")
  File "C:\Users\Iam\miniconda3\envs\mssenv\lib\site-packages\pint\facets\plain\registry.py", line 422, in define
    self._helper_dispatch_adder(definition)
  File "C:\Users\Iam\miniconda3\envs\mssenv\lib\site-packages\pint\facets\plain\registry.py", line 445, in _helper_dispatch_adder
    adder_func(definition)
  File "C:\Users\Iam\miniconda3\envs\mssenv\lib\site-packages\pint\facets\group\registry.py", line 82, in _add_unit
    super()._add_unit(definition)
  File "C:\Users\Iam\miniconda3\envs\mssenv\lib\site-packages\pint\facets\nonmultiplicative\registry.py", line 69, in _add_unit
    super()._add_unit(definition)
  File "C:\Users\Iam\miniconda3\envs\mssenv\lib\site-packages\pint\facets\plain\registry.py", line 512, in _add_unit
    self._helper_adder(definition, self._units, self._units_casei)
  File "C:\Users\Iam\miniconda3\envs\mssenv\lib\site-packages\pint\facets\plain\registry.py", line 451, in _helper_adder
    self._helper_single_adder(
  File "C:\Users\Iam\miniconda3\envs\mssenv\lib\site-packages\pint\facets\plain\registry.py", line 473, in _helper_single_adder
    raise RedefinitionError(key, type(value))
pint.errors.RedefinitionError: Cannot redefine 'ppm' (<class 'pint.delegates.txt_defparser.plain.UnitDefinition'>)
(mssenv) PS C:\WINDOWS\system32> which msui
/c/Users/Tanja/miniconda3/envs/mssenv/Scripts/msui 
```

**Comment by ReimarBauer** [comment]
pint-0.21 was released
https://anaconda.org/conda-forge/pint

new units were added

```
percent = 0.01 = %
ppm = 1e-6
```

https://github.com/hgrecco/pint/compare/0.20...0.21#diff-cc2784e7cfe7c2d896ae4ec1ef1563eed99bed539cb02f5a0f00e276dab48fe5R153

**Comment by ReimarBauer** [comment]
a workaround until a new build or release is available

```
mamba activate mssenv
mamba install pint==0.20.1
```

**Comment by ReimarBauer** [comment]
new build on the way
https://github.com/conda-forge/mss-feedstock/pull/151/files
