### ISSUE TITLE
default wms server from config not accessible

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1803]
besides the localhost builtin url the other two don't work
```
default_WMS = [
        "http://localhost:8081/",
        "http://eumetview.eumetsat.int/geoserver/wms",
        "https://apps.ecmwf.int/wms/?token=public"
    ]

```

**Comment by ReimarBauer** [comment]
90 % of this loads 
https://view.eumetsat.int/geoserver/wms

then
```
ERROR: Can't understand time string '2022-12-09T00:45:00.000Z/2023-08-10T08:45:00.000Z/P'. Please check the implementation.
ERROR: Cannot determine valid time format of https://view.eumetsat.int/geoserver/wms for Blended SEVIRI / LEO MW precipitation and morphologic information - MSG - 0 degree | msg_fes:h60b
ERROR: Can't understand time string '2022-12-09T08:00:00.000Z/2023-08-09T19:45:00.000Z/P'. Please check the implementation.
ERROR: Cannot determine valid time format of https://view.eumetsat.int/geoserver/wms for Precipitation rate at ground by GEO/IR supported by LEO/MW - MSG - Indian Ocean | msg_iodc:h63
ERROR: Can't understand time string '2023-03-07T11:15:00.000Z/2023-08-10T09:00:00.000Z/P'. Please check the implementation.
ERROR: Cannot determine valid time format of https://view.eumetsat.int/geoserver/wms for Rapidly Developing Thunderstorms - MSG - 0 degree | msg_fes:rdt

```
retrieving GetCapabilities freaks out on using all my system memory

**Comment by ReimarBauer** [comment]
This uses the figure attr and not fig
http://eccharts.ecmwf.int/wms/?token=public
a view data can be shown



![data_ecchart](https://github.com/Open-MSS/MSS/assets/278728/c2b4aa69-2741-4a0f-91c9-9d12b340a974)

**Comment by ReimarBauer** [comment]
We don't change this in 8.2 because alternative services use a different attribute.

**Comment by ReimarBauer** [comment]
```
CRITICAL: Fatal error: Traceback (most recent call last):
  File "/home/reimar/MAIN/MSS/mslib/msui/wms_control.py", line 1383, in continue_retrieve_image
    self.display_retrieved_image(img, legend_img, layer, style, init_time, valid_time, complete_level)
  File "/home/reimar/MAIN/MSS/mslib/msui/wms_control.py", line 1629, in display_retrieved_image
    self.view.draw_legend(self.append_multiple_images(legend_imgs))
  File "/home/reimar/MAIN/MSS/mslib/msui/wms_control.py", line 1484, in append_multiple_images
    max_height = int((self.view.plotter.fig.get_size_inches() * self.view.plotter.get_dpi())[1] * 0.99)
AttributeError: 'TopViewPlotter' object has no attribute 'get_dpi'
```
it shows an image

![ecmwf](https://github.com/Open-MSS/MSS/assets/278728/2a0f8528-1639-42ff-8ea6-60fc10895a33)

**Comment by ReimarBauer** [comment]
@joernu76 that would be pretty good when we could display http://eccharts.ecmwf.int/wms/?token=public
Could you have a look on this?
