### ISSUE TITLE
Crash/unhandled Exception during mscolab login (on bad connection)

### ISSUE THREAD

**Issue by joernu76** [Open-MSS/MSS#1830]
[msui.log](https://github.com/Open-MSS/MSS/files/12159297/msui.log)

**Comment by joernu76** [comment]
More instances of this occuring on bad connection:

```
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/site-packages/urllib3/connection.py", line 642, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/site-packages/urllib3/connection.py", line 783, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 469, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 513, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
TimeoutError: _ssl.c:980: The handshake operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/site-packages/urllib3/connectionpool.py", line 469, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/site-packages/urllib3/connectionpool.py", line 370, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='forecast.fz-juelich.de', port=443): Read timed out. (read timeout=2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/site-packages/mslib/msui/mscolab.py", line 927, in operation_options_handler
    self.open_admin_window()
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/site-packages/mslib/msui/mscolab.py", line 974, in open_admin_window
    self.admin_window = maw.MSColabAdminWindow(
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/site-packages/mslib/msui/mscolab_admin_window.py", line 90, in __init__
    self.load_users_with_permission()
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/site-packages/mslib/msui/mscolab_admin_window.py", line 231, in load_users_with_permission
    res = requests.get(url, data=data, timeout=(2, 10))
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='forecast.fz-juelich.de', port=443): Read timed out. (read timeout=2)
```

**Comment by joernu76** [comment]
and more
```
2023-07-25 11:40:03,198 (qt.excepthook:185): CRITICAL: Python Version: 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:23:14) [GCC 10.4.0]
2023-07-25 11:40:03,209 (qt.excepthook:186): CRITICAL: Platform: Linux-6.1.0-10-amd64-x86_64-with-glibc2.36 (('64bit', 'ELF'))
2023-07-25 11:40:03,209 (qt.excepthook:187): CRITICAL: Fatal error: Traceback (most recent call last):
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/site-packages/urllib3/connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/site-packages/urllib3/connection.py", line 212, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f63265baaa0>, 'Connection to forecast.fz-juelich.de timed out. (connect timeout=2)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='forecast.fz-juelich.de', port=443): Max retries exceeded with url: //operations (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f63265baaa0>, 'Connection to forecast.fz-juelich.de timed out. (connect timeout=2)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/site-packages/mslib/msui/mscolab.py", line 1253, in operation_category_handler
    self.add_operations_to_ui()
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/site-packages/mslib/msui/mscolab.py", line 1497, in add_operations_to_ui
    r = requests.get(f'{self.mscolab_server_url}/operations', data=data, timeout=(2, 10))
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/anaconda3/envs/mss-8.1.1/lib/python3.10/site-packages/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='forecast.fz-juelich.de', port=443): Max retries exceeded with url: //operations (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f63265baaa0>, 'Connection to forecast.fz-juelich.de timed out. (connect timeout=2)'))

```

**Comment by ReimarBauer** [comment]
We can try to optimize our reconnect functonality

https://github.com/Open-MSS/MSS/blob/develop/mslib/msui/socket_control.py#L57
There are some more parameters 

or we set it to infinite. I can't remember why we decided to set it to 5. 

https://socket.io/docs/v3/client-api/#Socket

@plant99 How would this these days be configured?

**Comment by plant99** [comment]
Hi Reimar, Joern!

I think `reconnection_attempts = 5` setting is very optimistic, as it's visible now. It would have been a random number I'm sure.

In my opinion, a good logic would be to ([reference](https://python-socketio.readthedocs.io/en/latest/api.html#client-class))
- remove this `reconnection_attempts` argument(the default is infinite -- like Reimar suggests).
- passing `reconnection_delay=1` as argument (unless there is a default value).
- Note that [exponential back-off](https://en.wikipedia.org/wiki/Exponential_backoff) is enabled by default and `reconnection_delay_max` should be set to something like 512 to avoid the UI hanging for a long time.

**Comment by joernu76** [comment]
I think, we need to capture RequestExceptions on *every* requests.post etc action and capture them sensibly. I am in the process of making a draft.

My internet was veery bad, but the program should still not crash in this fashion.

**Comment by ReimarBauer** [comment]
We have to be careful with request versus event.

We have already `"mscolab_skip_verify_user_token": false,` By this we checks on any request if the token is valid.  On a good internet collection this slows down the connection. It also logsout you in the UI which is usually not needed because you have a valid token, you are just lost the stream. I agree that we have to escape the tracebacks but not on the costs of a speedy connection.

default is that we skip  that verification by true.

**Comment by ReimarBauer** [comment]
> * reconnection_delay_max

playing with this in the current train :)

reconnection_delay_max should may  be not too high. Not sure I had a Segmentation fault after some time of reconnects
