### ISSUE TITLE
Usercreation broken

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1831]
```
tail mscolab-error.log
Traceback (most recent call last):
  File "/home/mss-mscolab/mambaforge/envs/mssenv/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mss-mscolab/mambaforge/envs/mssenv/lib/python3.9/site-packages/flask/app.py", line 1487, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/mss-mscolab/mambaforge/envs/mssenv/lib/python3.9/site-packages/flask/app.py", line 1506, in finalize_request
    response = self.make_response(rv)
  File "/home/mss-mscolab/mambaforge/envs/mssenv/lib/python3.9/site-packages/flask/app.py", line 1801, in make_response
    raise TypeError(
TypeError: The view function for 'user_register_handler' did not return a valid response. The function either returned None or ended without a return statement.
```

**Comment by joernu76** [comment]
In case that result["success"] is false or an unexpected Expcetion is thrown, no value is returned.
I do not understand that fully, but this should certainly be fixed and hotpatched.

**Comment by ReimarBauer** [comment]
The user creation works when not the e-mail or the name are in the system.  I now have many rb* accounts there.

These are the outputs I created, but I have not got an email
```
{'success': False, 'message': 'Oh no, this email ID is already taken!'}
>>> with app.app_context():
...      register_user("rb.proj+rb2@gmail.com", "meins", "rb2")
... 
{'success': False, 'message': 'Oh no, this username is already registered'}
>>> with app.app_context():
...      register_user("rb.proj+rb3@gmail.com", "meins", "rb3")
... 
{'success': False, 'message': 'Oh no, this email ID is already taken!'}
>>> with app.app_context():
...      register_user("rb.proj+rb4@gmail.com", "meins", "rb4")
... 
{'success': True}
```

accounts are not activated
