### ISSUE TITLE
traceback on another public WMS server

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1835]
https://www.geobasisdaten.niedersachsen.de/doorman/noauth/bestand

```
Fatal error in MSS 8.1.1 on Linux-6.2.0-10018-tuxedo-x86_64-with-glibc2.35
Python 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:23:14) [GCC 10.4.0]

Please report bugs in MSS to https://github.com/Open-MSS/MSS

Information about the fatal error:

Traceback (most recent call last):
  File "/home/reimar/mambaforge/envs/mssenv/lib/python3.10/site-packages/mslib/msui/wms_control.py", line 1383, in continue_retrieve_image
    self.display_retrieved_image(img, legend_img, layer, style, init_time, valid_time, complete_level)
  File "/home/reimar/mambaforge/envs/mssenv/lib/python3.10/site-packages/mslib/msui/wms_control.py", line 1639, in display_retrieved_image
    self.view.draw_legend(self.append_multiple_images(legend_imgs))
  File "/home/reimar/mambaforge/envs/mssenv/lib/python3.10/site-packages/mslib/msui/wms_control.py", line 1484, in append_multiple_images
    max_height = int((self.view.fig.get_size_inches() * self.view.fig.get_dpi())[1] * 0.99)
AttributeError: 'MplTopViewCanvas' object has no attribute 'fig'
```

**Comment by ReimarBauer** [comment]
https://geoportal2.duisburg.de/arcgisserver/services/Basisdaten/DGK_hist_Portal/MapServer/WMSServer
https://geoportal2.duisburg.de/arcgisserver/services/Luftbilder/Historische_Luftbilder/MapServer/WMSServer

Fatal error in MSS 8.1.1 on Linux-6.2.0-10018-tuxedo-x86_64-with-glibc2.35
Python 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:23:14) [GCC 10.4.0]

Please report bugs in MSS to https://github.com/Open-MSS/MSS

Information about the fatal error:

```
Traceback (most recent call last):
  File "/home/reimar/mambaforge/envs/mssenv/lib/python3.10/site-packages/mslib/msui/wms_control.py", line 1383, in continue_retrieve_image
    self.display_retrieved_image(img, legend_img, layer, style, init_time, valid_time, complete_level)
  File "/home/reimar/mambaforge/envs/mssenv/lib/python3.10/site-packages/mslib/msui/wms_control.py", line 1639, in display_retrieved_image
    self.view.draw_legend(self.append_multiple_images(legend_imgs))
  File "/home/reimar/mambaforge/envs/mssenv/lib/python3.10/site-packages/mslib/msui/wms_control.py", line 1484, in append_multiple_images
    max_height = int((self.view.fig.get_size_inches() * self.view.fig.get_dpi())[1] * 0.99)
AttributeError: 'MplTopViewCanvas' object has no attribute 'fig
```

**Comment by ReimarBauer** [comment]
https://sg.geodatenzentrum.de/wms_dtk_bkg

same failure

**Comment by ReimarBauer** [comment]
https://www.wms.nrw.de/umwelt/wasser/uesg

same failure

**Comment by ReimarBauer** [comment]
https://umweltgeodienste.schleswig-holstein.de/WMS_UWAT_NAT

**Comment by ReimarBauer** [comment]
https://www.gpdn.de/wilma.aspx?pgId=432

e.g.
```
ERROR: We cannot load the capability document!

<class 'owslib.util.ServiceException'>
Mind. einer der Parameter PKGID, NODEID muss definiert werden.
```

**Comment by ReimarBauer** [comment]
https://geodienste.ch/db/av_0/deu

**Comment by ReimarBauer** [comment]
> 

there own service shows failures
https://www.gpdn.de/public/ogc.ashx?Service=WMS&PkgId=10&Request=GetCapabilities

```
<ServiceExceptionReport version="1.1.0">
<ServiceException code="System.Data.SqlClient.SqlException" locator="">Ungültiger Spaltenname "EXTENSION_JSON".</ServiceException>
</ServiceExceptionReport>
```

**Comment by ReimarBauer** [comment]
The tracebacks are solved, we may need to add another method if needed to display these data.
