### ISSUE TITLE
develop problem with creating users

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1836]
I tried to create a bunch of test users in develop, on the second testuser it shows.
 
```
Fatal error in MSS 8.1.1 on Linux-6.2.0-10018-tuxedo-x86_64-with-glibc2.35
Python 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:23:14) [GCC 10.4.0]

Please report bugs in MSS to https://github.com/Open-MSS/MSS

Information about the fatal error:

Traceback (most recent call last):
  File "/home/reimar/PycharmProjects/MSS/mslib/msui/mscolab.py", line 387, in new_user_handler
    self.save_user_credentials_to_config_file(emailid, password)
  File "/home/reimar/PycharmProjects/MSS/mslib/msui/mscolab.py", line 335, in save_user_credentials_to_config_file
    save_password_to_keyring(service_name=self.mscolab_server_url, username=emailid, password=password)
  File "/home/reimar/PycharmProjects/MSS/mslib/utils/auth.py", line 78, in save_password_to_keyring
    keyring.set_password(service_name=service_name, username=username, password=password)
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/keyring/core.py", line 60, in set_password
    get_keyring().set_password(service_name, username, password)
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/keyring/backends/SecretService.py", line 91, in set_password
    collection.create_item(label, attributes, password, replace=True)
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/secretstorage/collection.py", line 118, in create_item
    self.session = open_session(self.connection)
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/secretstorage/util.py", line 80, in open_session
    output, result = service.call(
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/secretstorage/util.py", line 63, in call
    return self.send_and_get_reply(msg)
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/secretstorage/util.py", line 48, in send_and_get_reply
    raise DBusErrorResponse(resp_msg)
jeepney.wrappers.DBusErrorResponse: [org.freedesktop.DBus.Error.InvalidArgs] ('Client public key size is invalid',)
```

**Comment by ReimarBauer** [comment]
can't reproduce
