### ISSUE TITLE
Linearview and Sideview crash on Clear figure by clicking on the remove button

### ISSUE THREAD

**Issue by dhgkunkel** [Open-MSS/MSS#1857]
In side view when pushing the button "remove", I get the following error:

Please report bugs in MSS to https://github.com/Open-MSS/MSS

Information about the fatal error:

Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/mssenv/lib/python3.10/site-packages/mslib/msui/wms_control.py", line 709, in clear_map
    self.view.clear_figure()
AttributeError: 'MplSideViewCanvas' object has no attribute 'clear_figure'

**Comment by ReimarBauer** [comment]
Same problem also in LinearView

```
Traceback (most recent call last):
  File "/home/reimar/mambaforge/envs/mssenv/lib/python3.10/site-packages/mslib/msui/wms_control.py", line 709, in clear_map
    self.view.clear_figure()
AttributeError: 'MplLinearViewCanvas' object has no attribute 'clear_figure'
CRITICAL: MSS Version: 8.1.1
CRITICAL: Python Version: 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:23:14) [GCC 10.4.0]
CRITICAL: Platform: Linux-6.2.0-10018-tuxedo-x86_64-with-glibc2.35 (('64bit', 'ELF'))
CRITICAL: Fatal error: Traceback (most recent call last):
  File "/home/reimar/mambaforge/envs/mssenv/lib/python3.10/site-packages/mslib/msui/wms_control.py", line 709, in clear_map
    self.view.clear_figure()
AttributeError: 'MplLinearViewCanvas' object has no attribute 'clear_figure'
```
