### ISSUE TITLE
After MSColab Server restart, MSUI had a crash

### ISSUE THREAD

**Issue by joernu76** [Open-MSS/MSS#1862]
![Screenshot at 2023-08-08 09-53-15](https://github.com/Open-MSS/MSS/assets/28449201/eb06c52c-baf5-4fc2-83b3-22e5f45613ee)

```
2023-08-08 09:52:55,323 (mscolab.reload_view_windows:1781): DEBUG: reload_view_windows
2023-08-08 09:52:56,329 (mscolab.switch_to_local:1646): DEBUG: switch_to_local
2023-08-08 09:52:56,329 (msui_mainwindow.update_active_flight_track:729): DEBUG: update_active_flight_track
2023-08-08 09:52:56,467 (qt.excepthook:183): CRITICAL: MSS Version: 8.1.1
2023-08-08 09:52:56,467 (qt.excepthook:184): CRITICAL: Python Version: 3.10.11 | packaged by conda-forge | (main, May 10 2023, 18:58:44) [GCC 11.3.0]
2023-08-08 09:52:56,472 (qt.excepthook:185): CRITICAL: Platform: Linux-6.1.0-10-amd64-x86_64-with-glibc2.36 (('64bit', 'ELF'))
2023-08-08 09:52:56,472 (qt.excepthook:186): CRITICAL: Fatal error: Traceback (most recent call last):
  File "/home/icg173/src/mss/mslib/msui/mscolab.py", line 1320, in reload_operation_list
    if operations:
  File "/home/icg173/src/mss/mslib/msui/mscolab.py", line 1758, in reload_operations
    index = self.ui.filterCategoryCb.findText(selected_category, QtCore.Qt.MatchFixedString)
  File "/home/icg173/src/mss/mslib/msui/mscolab.py", line 1462, in show_categories_to_ui
    if op_id == old_active_id and operation_name is None:
  File "/opt/anaconda3/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/opt/anaconda3/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/anaconda3/lib/python3.10/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "/opt/anaconda3/lib/python3.10/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/opt/anaconda3/lib/python3.10/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/opt/anaconda3/lib/python3.10/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'None/operations': No scheme supplied. Perhaps you meant https://None/operations?
```

**Comment by joernu76** [comment]
The error came twice after API/login required info box.

**Comment by joernu76** [comment]
The error occured in *develop* not stable.

**Comment by ReimarBauer** [comment]
A fresh started develop version can login again.

The line looks different to the shown. Do you have a different branch?
https://github.com/Open-MSS/MSS/blob/develop/mslib/msui/mscolab.py#L1462

**Comment by joernu76** [comment]
It was this version
514c823d785614f8bdf0f5e5db7eb98f1bc8bed1

**Comment by joernu76** [comment]
Or not. I am confused. Maybe the source code was exchanged while the program was running.

**Comment by ReimarBauer** [comment]
Usally it recognizes that the token is invalid.

Let us close this for now and reopen  when we can better describe this.
