### ISSUE TITLE
develop connect sometimes fatal error

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1946]
```
Fatal error in MSS 8.2.0 on Linux-6.2.0-10018-tuxedo-x86_64-with-glibc2.35
Python 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:23:14) [GCC 10.4.0]

Please report bugs in MSS to https://github.com/Open-MSS/MSS

Information about the fatal error:

Traceback (most recent call last):
  File "/home/reimar/MAIN/MSS/mslib/msui/mscolab.py", line 176, in mscolab_login_changed
    get_password_from_keyring(self.mscolab_server_url, text))
  File "/home/reimar/MAIN/MSS/mslib/utils/auth.py", line 60, in get_password_from_keyring
    cred = keyring.get_credential(service_name=service_name, username=username)
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/keyring/core.py", line 72, in get_credential
    return get_keyring().get_credential(service_name, username)
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/keyring/backends/SecretService.py", line 119, in get_credential
    return SimpleCredential(username, item.get_secret().decode('utf-8'))
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/secretstorage/item.py", line 99, in get_secret
    self.session = open_session(self.connection)
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/secretstorage/util.py", line 80, in open_session
    output, result = service.call(
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/secretstorage/util.py", line 63, in call
    return self.send_and_get_reply(msg)
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/secretstorage/util.py", line 48, in send_and_get_reply
    raise DBusErrorResponse(resp_msg)
jeepney.wrappers.DBusErrorResponse: [org.freedesktop.DBus.Error.InvalidArgs] ('Client public key size is invalid',)
```

**Comment by ReimarBauer** [comment]
connection worked, after OK
