### ISSUE TITLE
develop: update of attributes behave wrong on server restarts

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1947]
With the option to verify the token it crashes, with the default and only doing this change call. It just did not change the category and also did not logout.
```
Fatal error in MSS 8.2.0 on Linux-6.2.0-10018-tuxedo-x86_64-with-glibc2.35
Python 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:23:14) [GCC 10.4.0]

Please report bugs in MSS to https://github.com/Open-MSS/MSS

Information about the fatal error:

Traceback (most recent call last):
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Verbindungsaufbau abgelehnt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fa51a59edd0>: Failed to establish a new connection: [Errno 111] Verbindungsaufbau abgelehnt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8083): Max retries exceeded with url: /update_operation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa51a59edd0>: Failed to establish a new connection: [Errno 111] Verbindungsaufbau abgelehnt'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/reimar/MAIN/MSS/mslib/msui/mscolab.py", line 1129, in change_category_handler
    r = requests.post(url, data=data, timeout=tuple(config_loader(dataset="MSCOLAB_timeout")))
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8083): Max retries exceeded with url: /update_operation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa51a59edd0>: Failed to establish a new connection: [Errno 111] Verbindungsaufbau abgelehnt'))

```

**Comment by ReimarBauer** [comment]
same problem on change description

**Comment by ReimarBauer** [comment]
rename_operation
