### ISSUE TITLE
'QTextEdit' object is not callable

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#196]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/196) by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

enabling service_abstract = "Your Abstract" gives this traceback

```
#!python

Traceback (most recent call last):
  File "/home/user/PycharmProjects/mss/mslib/msui/wms_control.py", line 675, in getCapabilities
    self.activateWMS(wms)
  File "/home/user/PycharmProjects/mss/mslib/msui/wms_control.py", line 704, in activateWMS
    self.layerChanged(0)
  File "/home/user/PycharmProjects/mss/mslib/msui/wms_control.py", line 821, in layerChanged
    self.teLayerAbstract(abstract_text)
TypeError: 'QTextEdit' object is not callable
```

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

service_abstract = "Your Abstract"  is not related to the lines there. needs more investigation

* teLayerAbstract is used to set an abstract based on a Layer. 

* service_abstract is for the global abstract

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

not reproducible, reopen if you have mor informations
