### ISSUE TITLE
develop: problem with multiple flightpath

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#2044]
```
Fatal error in MSS 8.3.0 on Linux-6.2.0-10022-tuxedo-x86_64-with-glibc2.35
Python 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:23:14) [GCC 10.4.0]

Please report bugs in MSS to https://github.com/Open-MSS/MSS

Information about the fatal error:

Traceback (most recent call last):
  File "/home/reimar/MAIN/MSS/mslib/msui/topview.py", line 355, in openTool
    widget = mf.MultipleFlightpathControlWidget(parent=self, view=self.mpl.canvas,
  File "/home/reimar/MAIN/MSS/mslib/msui/multiple_flightpath_dockwidget.py", line 165, in __init__
    self.connect_mscolab_server()
  File "/home/reimar/MAIN/MSS/mslib/msui/multiple_flightpath_dockwidget.py", line 198, in connect_mscolab_server
    self.operations = MultipleFlightpathOperations(self, self.mscolab_server_url, self.token,
  File "/home/reimar/MAIN/MSS/mslib/msui/multiple_flightpath_dockwidget.py", line 534, in __init__
    xml_content = self.request_wps_from_server(op_id)
  File "/home/reimar/MAIN/MSS/mslib/msui/multiple_flightpath_dockwidget.py", line 577, in request_wps_from_server
    xml_content = json.loads(r.text)["content"]
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by ReimarBauer** [comment]
on a recreated database also the colabdata dir has to be recreated
