### ISSUE TITLE
develop:multiple_flightpath_dockwidget problem with gcpoints_path

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#2045]
```

CRITICAL: MSS Version: 8.3.0
CRITICAL: Python Version: 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:23:14) [GCC 10.4.0]
CRITICAL: Platform: Linux-6.2.0-10022-tuxedo-x86_64-with-glibc2.35 (('64bit', 'ELF'))
CRITICAL: Fatal error: Traceback (most recent call last):
  File "/home/reimar/MAIN/MSS/mslib/msui/multiple_flightpath_dockwidget.py", line 551, in set_flag
    self.draw_inactive_operations()
  File "/home/reimar/MAIN/MSS/mslib/msui/multiple_flightpath_dockwidget.py", line 662, in draw_inactive_operations
    patch = MultipleFlightpath(self.view.map,
  File "/home/reimar/MAIN/MSS/mslib/msui/multiple_flightpath_dockwidget.py", line 66, in __init__
    self.draw()
  File "/home/reimar/MAIN/MSS/mslib/msui/multiple_flightpath_dockwidget.py", line 93, in draw
    x, y = self.compute_xy(lon, lat)
  File "/home/reimar/MAIN/MSS/mslib/msui/multiple_flightpath_dockwidget.py", line 72, in compute_xy
    x, y = self.map.gcpoints_path(lon, lat)
  File "/home/reimar/MAIN/MSS/mslib/msui/mpl_map.py", line 721, in gcpoints_path
    assert len(lons) > 1
AssertionError
```

**Comment by ReimarBauer** [comment]
this can also happen when the database was migrated while an operation gets renamed.
