### ISSUE TITLE
on sideview by using GetCapabilities a traceback occured

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#2107]
Fatal error in MSS 8.3.1 on Linux-6.5.0-10008-tuxedo-x86_64-with-glibc2.35
Python 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:23:14) [GCC 10.4.0]

Please report bugs in MSS to https://github.com/Open-MSS/MSS

Information about the fatal error:

Traceback (most recent call last):
  File "/home/reimar/PycharmProjects/MSS/mslib/msui/wms_control.py", line 596, in on_success
    self.activate_wms(wms)
  File "/home/reimar/PycharmProjects/MSS/mslib/msui/wms_control.py", line 783, in activate_wms
    self.prefetch.disconnect(self.prefetcher.fetch_maps)
TypeError: disconnect() failed between 'prefetch' and 'fetch_maps'

**Comment by matrss** [comment]
I think I have seen this issue as well as intermittent test failures in #2100. I suspect that this has something to do with how the QThreads are setup and the destructor is overloaded there (which looks like it is not what should be done there).

**Comment by ReimarBauer** [comment]
This seems not to happen often, no user complaining yet,  I think we can shift it to 10.0

**Comment by matrss** [comment]
I've seen this kind of issue coming from wms_control.py when trying to close all widgets after each test. There seemed to be some kind of race condition in the object destruction. I *think* this issue is more pronounced when opening and closing the windows happens with little delay, as it happens in the test suite. So maybe this is less of an issue in the real world, as you say.

Also, I have no clue yet on how to fix this.
