### ISSUE TITLE
enable saving as svg, pdf image 

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#2135]
when I want to store a multiple flightpath created image I get

```
INFO: MSS Version: 8.3.1
INFO: Python Version: 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:23:14) [GCC 10.4.0]
INFO: Platform: Linux-6.5.0-10013-tuxedo-x86_64-with-glibc2.35 (('64bit', 'ELF'))
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 42908, resource id: 27275660, major code: 40 (TranslateCoords), minor code: 0
Traceback (most recent call last):
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/matplotlib/cbook/__init__.py", line 309, in process
    func(*args, **kwargs)
  File "/home/reimar/PycharmProjects/MSS/mslib/msui/mpl_pathinteractor.py", line 588, in draw_callback
    super().draw_callback(event)
  File "/home/reimar/PycharmProjects/MSS/mslib/msui/mpl_pathinteractor.py", line 390, in draw_callback
    self.ax.draw_artist(self.pathpatch)
  File "/home/reimar/mambaforge/envs/mssdev/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 3074, in draw_artist
    a.draw(self.figure.canvas.get_renderer())
AttributeError: 'FigureCanvasSVG' object has no attribute 'get_renderer'
```

**Comment by ReimarBauer** [comment]
This is a matplotlib problem and it is solved with the updated version. At the time we release 9.0.0 it is fixed.
