### ISSUE TITLE
develop: switching the active operation to a local flightpath gives a traceback in multiple flightpath

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#2142]
This should be fixed in develop, we don't want a API change in stable

```
Fatal error in MSS 8.3.2 on Linux-6.5.0-10013-tuxedo-x86_64-with-glibc2.35
Python 3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:17) [GCC 12.2.0]

Please report bugs in MSS to https://github.com/Open-MSS/MSS

Information about the fatal error:

Traceback (most recent call last):
  File "/home/reimar/PycharmProjects/MSS/mslib/msui/multiple_flightpath_dockwidget.py", line 391, in set_linewidth
    self.operations.set_linewidth()
  File "/home/reimar/PycharmProjects/MSS/mslib/msui/multiple_flightpath_dockwidget.py", line 803, in set_linewidth
    self.dict_operations[op_id]["patch"].remove()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'remove'
```

**Comment by ReimarBauer** [comment]
![not_reproducable](https://github.com/Open-MSS/MSS/assets/278728/26a8b7f5-c4e4-4fcb-999a-95acf38a7fba)

this seems to be fixed by some other change
