### ISSUE TITLE
with defaults mscolab.py db --seed crashes -> idp_config['idp_data']['assertion_consumer_endpoints']:

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#2212]
```

python mslib/mscolab/mscolab.py db --seed
WARNING:root:Couldn't import setup_saml2_backend (ImportError:'No module named 'setup_saml2_backend''), using dummy config.
WARNING:root:Couldn't import mscolab_auth (ImportError:'{No module named 'mscolab_auth'), creating dummy config.
Traceback (most recent call last):
  File "/home/reimar/PycharmProjects/MSS/mslib/mscolab/mscolab.py", line 40, in <module>
    from mslib.mscolab.seed import seed_data, add_user, add_all_users_default_operation, \
  File "/home/reimar/PycharmProjects/MSS/mslib/mscolab/seed.py", line 36, in <module>
    from mslib.mscolab.server import APP as app
  File "/home/reimar/PycharmProjects/MSS/mslib/mscolab/server.py", line 836, in <module>
    for assertion_consumer_endpoint in idp_config['idp_data']['assertion_consumer_endpoints']:
                                       ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by ReimarBauer** [comment]
there was a USE_SAML2 = True, but not endpoints defined
