### ISSUE TITLE
Find a way to split into different packages with same codebase

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#2307]
It's just important to me that we don't lose the namespace

We don't want to split the repository, because we have many mutual dependencies. Otherwise it usually becomes much smaller than you initially plan. All in all, that's a lot of overhead for the same number of developers.

Also related
https://github.com/conda-forge/mss-feedstock/issues/165

On conda-forge each setup.py would need the proper entrypoints, but there it can be patched.

_Originally posted by @ReimarBauer in https://github.com/Open-MSS/MSS/issues/2294#issuecomment-2023379052_

**Comment by ReimarBauer** [comment]
mswms imports stuff from the MSUI

```
mslib/mswms/mswms.py", line 34, in <module>
    from mslib.utils.qt import Updater, Worker

mslib/utils/qt.py", line 36, in <module>
    from fslib.fs_filepicker import getSaveFileName, getOpenFileName, getExistingDirectory
```

That is only needed for the updater.

**Comment by ReimarBauer** [comment]
```
Traceback (most recent call last):
  File "/home/user/Miniforge/conda-bld/mss_1716454757865/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/mswms", line 7, in <module>
    from mslib.mswms.mswms import main
  File "/home/user/Miniforge/conda-bld/mss_1716454757865/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.10/site-packages/mslib/mswms/mswms.py", line 35, in <module>
    from mslib.mswms.wms import app as application
  File "/home/user/Miniforge/conda-bld/mss_1716454757865/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.10/site-packages/mslib/mswms/wms.py", line 145, in <module>
    from mslib.mswms import mss_plot_driver
  File "/home/user/Miniforge/conda-bld/mss_1716454757865/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.10/site-packages/mslib/mswms/mss_plot_driver.py", line 38, in <module>
    import mslib.utils.coordinate as coordinate
  File "/home/user/Miniforge/conda-bld/mss_1716454757865/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.10/site-packages/mslib/utils/coordinate.py", line 36, in <module>
    from mslib.utils.config import config_loader
  File "/home/user/Miniforge/conda-bld/mss_1716454757865/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.10/site-packages/mslib/utils/config.py", line 28, in <module>
    from PyQt5 import QtCore
ModuleNotFoundError: No module named 'PyQt5'

```
the config_loader is only MSUI 

find_location   should be separated
