### ISSUE TITLE
Test docs build misses execfile on our setup for RTFD

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#2378]
That is different to stable 8.3.5 currently

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/mss/conda/develop/lib/python3.11/site-packages/sphinx/config.py", line 509, in eval_config_file
    exec(code, namespace)  # NoQA: S102
    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/mss/checkouts/develop/docs/conf.py", line 105, in <module>
    execfile('../mslib/version.py')
    ^^^^^^^^
NameError: name 'execfile' is not defined


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/mss/conda/develop/lib/python3.11/site-packages/sphinx/config.py", line 509, in eval_config_file
    exec(code, namespace)  # NoQA: S102
    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/mss/checkouts/develop/docs/conf.py", line 105, in <module>

```

**Comment by ReimarBauer** [comment]
the log says:
```
2024-05-20 18:56:02          write_html || plots.html created at /tmp/tmp2j49365k/plots.html
2024-05-20 18:56:02            <module> || No module named 'past'
```
we can explicitly add it by the future module.


`from past.builtins import execfile`
