### ISSUE TITLE
pyproj 3.5.0 libcurl.so.4: undefined symbol:

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#2387]
The testwsgi script succeeds but when I want to run the application it ends with a libcurl error

```
Client 127.0.0.1:37096] request declined in mgs_hook_fixups
mod_wsgi (pid=13166, process='DEMO', application=''): Loading Python script file '/DEMO/wsgi/wms.wsgi'.
mod_wsgi (pid=13166): Failed to exec Python script file '/DEMO/wsgi/wms.wsgi'.
mod_wsgi (pid=13166): Exception occurred processing WSGI script 'wms.wsgi'.
Traceback (most recent call last):
  File "/DEMO/wsgi/wms.wsgi", line 29, in <module>
    from mslib.mswms.wms import app as application
  File "mssenv/lib/python3.10/site-packages/mslib/mswms/wms.py", line 67, in <module>
    from mslib.mswms.gallery_builder import add_image, write_html, add_levels, add_times, \\
  File "mssenv/lib/python3.10/site-packages/mslib/mswms/gallery_builder.py", line 35, in <module>
    from mslib.mswms.mpl_vsec import AbstractVerticalSectionStyle
  File "mssenv/lib/python3.10/site-packages/mslib/mswms/mpl_vsec.py", line 42, in <module>
    from mslib.utils.units import convert_to, units
  File "mssenv/lib/python3.10/site-packages/mslib/utils/units.py", line 31, in <module>
    from metpy.units import units, check_units  # noqa
  File "mssenv/lib/python3.10/site-packages/metpy/__init__.py", line 15, in <module>
    from .xarray import *  # noqa: F401, F403, E402
  File "mssenv/lib/python3.10/site-packages/metpy/xarray.py", line 26, in <module>
    from pyproj import CRS, Proj
  File "mssenv/lib/python3.10/site-packages/pyproj/__init__.py", line 33, in <module>
    import pyproj.network
  File "mssenv/lib/python3.10/site-packages/pyproj/network.py", line 10, in <module>
    from pyproj._network import (  # noqa: F401 pylint: disable=unused-import
ImportError: mssenv/lib/python3.10/site-packages/pyproj/../../.././libcurl.so.4: undefined symbol: nghttp2_option_set_no_rfc9113_leading_and_trailing_ws_validation
AH02001: Connection closed to child 512 with standard shutdown (server)
```

**Comment by ReimarBauer** [comment]
uwsgi has no problems yet

**Comment by ReimarBauer** [comment]
The problem exists since libcurl  > 7.87.0

**Comment by ReimarBauer** [comment]
https://github.com/conda-forge/curl-feedstock/issues/138

**Comment by ReimarBauer** [comment]
We can use a recent pyproj for mswms when we have splitted:
https://github.com/Open-MSS/MSS/issues/2307

then it can update
```

  - openjpeg            2.5.0  h7d73246_1       conda-forge     Cached
  + openjpeg            2.5.0  hfec8fc6_2       conda-forge     Cached

  Upgrade:
────────────────────────────────────────────────────────────────────────

  - ca-certificates  2024.2.2  hbcca054_0       conda-forge     Cached
  + ca-certificates  2024.6.2  hbcca054_0       conda-forge     Cached
  - libtiff             4.4.0  h82bc61c_5       conda-forge     Cached
  + libtiff             4.5.0  h82bc61c_0       conda-forge     Cached
  - openssl             3.3.0  h4ab18f5_3       conda-forge     Cached
  + openssl             3.3.1  h4ab18f5_0       conda-forge     Cached
  - lcms2                2.14  h6ed2654_0       conda-forge     Cached
  + lcms2                2.15  hfd0df8a_0       conda-forge     Cached
  - proj                9.1.1  h93bde94_0       conda-forge     Cached
  + proj                9.2.1  ha643af7_0       conda-forge     Cached
  - pillow              9.2.0  py311h9461556_3  conda-forge     Cached
  + pillow              9.4.0  py311h50def17_1  conda-forge     Cached
  - certifi          2024.2.2  pyhd8ed1ab_0     conda-forge     Cached
  + certifi          2024.6.2  pyhd8ed1ab_0     conda-forge     Cached
  - pyproj              3.5.0  py311h945b3ca_0  conda-forge     Cached
  + pyproj              3.6.1  py311ha169711_0  conda-forge     Cached
```
with all packages we can't

` qt-main is not installable because there are no viable options`

**Comment by ReimarBauer** [comment]
```
─ qt-main is not installable because there are no viable options
│  ├─ qt-main [5.15.6|5.15.8] would require
│  │  ├─ alsa-lib >=1.2.8,<1.2.9.0a0 , which can be installed;
│  │  ├─ icu >=70.1,<71.0a0 , which can be installed;
│  │  ├─ jpeg >=9e,<10a , which can be installed;
│  │  ├─ krb5 >=1.20.1,<1.21.0a0 , which conflicts with any installable versions previously reported;
│  │  └─ libpq >=15.1,<16.0a0  but there are no viable options
│  │     ├─ libpq 15.3 would require
│  │     │  └─ openssl >=3.1.0,<3.2.0a0 , which conflicts with any installable versions previously reported;
│  │     ├─ libpq 15.3 would require
│  │     │  └─ openssl >=3.1.1,<3.2.0a0 , which conflicts with any installable versions previously reported;
│  │     ├─ libpq 15.4 would require
│  │     │  └─ openssl >=3.2.0,<3.2.0a0 , which does not exist (perhaps a missing channel);
│  │     ├─ libpq [15.4|15.5] would require
│  │     │  └─ libxml2 [>=2.12.3,<3.0.0a0 |>=2.12.4,<3.0a0 ], which requires
│  │     │     └─ icu >=73.2,<74.0a0 , which conflicts with any installable versions previously reported;
│  │     ├─ libpq 15.4 would require
│  │     │  └─ openssl >=3.1.2,<3.2.0a0 , which conflicts with any installable versions previously reported;
│  │     ├─ libpq 15.4 would require
│  │     │  └─ openssl >=3.1.3,<3.2.0a0 , which conflicts with any installable versions previously reported;
│  │     ├─ libpq 15.6 would require
│  │     │  ├─ libxml2 >=2.12.5,<3.0a0 , which cannot be installed (as previously explained);
│  │     │  └─ openssl >=3.2.1,<4.0a0 , which can be installed;
│  │     ├─ libpq 15.7 would require
│  │     │  ├─ libxml2 >=2.12.6,<3.0a0 , which cannot be installed (as previously explained);
│  │     │  └─ openssl >=3.3.0,<4.0a0 , which can be installed;
│  │     ├─ libpq 15.2 would require
│  │     │  └─ openssl >=3.0.8,<3.2.0a0 , which conflicts with any installable versions previously reported;
│  │     ├─ libpq 15.1 would require
│  │     │  └─ openssl >=1.1.1s,<1.1.2a , which conflicts with any installable versions previously reported;
│  │     └─ libpq 15.1 would require
│  │        └─ openssl >=3.0.7,<3.2.0a0 , which conflicts with any installable versions previously reported;
│  ├─ qt-main 5.15.2 would require
│  │  ├─ krb5 >=1.19.2,<1.20.0a0 , which conflicts with any installable versions previously reported;
│  │  └─ openssl >=1.1.1l,<1.1.2a , which conflicts with any installable versions previously reported;
│  ├─ qt-main 5.15.2 would require
│  │  ├─ jpeg >=9e,<10a , which can be installed;
│  │  ├─ krb5 >=1.19.2,<1.20.0a0 , which conflicts with any installable versions previously reported;
│  │  └─ openssl >=1.1.1l,<1.1.2a , which conflicts with any installable versions previously reported;
│  ├─ qt-main 5.15.3 would require
│  │  ├─ jpeg >=9e,<10a , which can be installed;
│  │  ├─ krb5 >=1.19.3,<1.20.0a0 , which conflicts with any installable versions previously reported;
│  │  └─ openssl >=1.1.1n,<1.1.2a , which conflicts with any installable versions previously reported;
│  ├─ qt-main [5.15.3|5.15.4] would require
│  │  ├─ jpeg >=9e,<10a , which can be installed;
│  │  ├─ krb5 >=1.19.3,<1.20.0a0 , which conflicts with any installable versions previously reported;
│  │  └─ openssl >=1.1.1o,<1.1.2a , which conflicts with any installable versions previously reported;
│  ├─ qt-main 5.15.6 would require
│  │  ├─ jpeg >=9e,<10a , which can be installed;
│  │  ├─ krb5 >=1.19.3,<1.20.0a0 , which conflicts with any installable versions previously reported;
│  │  └─ openssl >=1.1.1q,<1.1.2a , which conflicts with any installable versions previously reported;
│  ├─ qt-main 5.15.6 would require
│  │  ├─ jpeg >=9e,<10a , which can be installed;
│  │  ├─ krb5 >=1.20.1,<1.21.0a0 , which conflicts with any installable versions previously reported;
│  │  └─ openssl >=1.1.1s,<1.1.2a , which conflicts with any installable versions previously reported;
│  ├─ qt-main 5.15.6 would require
│  │  ├─ jpeg >=9e,<10a , which can be installed;
│  │  ├─ krb5 >=1.19.3,<1.20.0a0 , which conflicts with any installable versions previously reported;
│  │  └─ openssl >=1.1.1s,<1.1.2a , which conflicts with any installable versions previously reported;
│  ├─ qt-main 5.15.6 would require
│  │  ├─ alsa-lib >=1.2.8,<1.2.9.0a0 , which can be installed;
│  │  ├─ icu >=70.1,<71.0a0 , which can be installed;
│  │  ├─ jpeg >=9e,<10a , which can be installed;
│  │  ├─ krb5 >=1.19.3,<1.20.0a0 , which conflicts with any installable versions previously reported;
│  │  └─ libpq >=15.1,<16.0a0 , which cannot be installed (as previously explained);
│  ├─ qt-main 5.15.8 would require
│  │  ├─ alsa-lib >=1.2.8,<1.2.9.0a0 , which can be installed;
│  │  ├─ icu >=72.1,<73.0a0 , which conflicts with any installable versions previously reported;
│  │  ├─ krb5 >=1.20.1,<1.21.0a0 , which conflicts with any installable versions previously reported;
│  │  ├─ libjpeg-turbo >=2.1.5.1,<3.0a0 , which cannot be installed (as previously explained);
│  │  └─ libpq >=15.3,<16.0a0 , which cannot be installed (as previously explained);
│  ├─ qt-main 5.15.8 would require
│  │  ├─ alsa-lib >=1.2.11,<1.3.0a0 , which conflicts with any installable versions previously reported;
│  │  ├─ icu >=73.2,<74.0a0 , which conflicts with any installable versions previously reported;
│  │  ├─ libjpeg-turbo >=3.0.0,<4.0a0 , which cannot be installed (as previously explained);
│  │  └─ openssl >=3.2.1,<4.0a0 , which can be installed;
│  ├─ qt-main 5.15.8 would require
│  │  ├─ alsa-lib >=1.2.10,<1.3.0.0a0 , which conflicts with any installable versions previously reported;
│  │  ├─ icu >=73.2,<74.0a0 , which conflicts with any installable versions previously reported;
│  │  ├─ libjpeg-turbo >=3.0.0,<4.0a0 , which cannot be installed (as previously explained);
│  │  └─ openssl >=3.2.0,<4.0a0 , which can be installed;
│  ├─ qt-main 5.15.8 would require
│  │  ├─ alsa-lib >=1.2.10,<1.3.0.0a0 , which conflicts with any installable versions previously reported;
│  │  ├─ icu >=73.2,<74.0a0 , which conflicts with any installable versions previously reported;
│  │  ├─ libjpeg-turbo >=3.0.0,<4.0a0 , which cannot be installed (as previously explained);
│  │  └─ openssl >=3.2.1,<4.0a0 , which can be installed;
│  ├─ qt-main 5.15.8 would require
│  │  ├─ alsa-lib >=1.2.8,<1.2.9.0a0 , which can be installed;
│  │  ├─ icu >=72.1,<73.0a0 , which conflicts with any installable versions previously reported;
│  │  ├─ krb5 >=1.20.1,<1.21.0a0 , which conflicts with any installable versions previously reported;
│  │  ├─ libjpeg-turbo >=2.1.5.1,<3.0a0 , which cannot be installed (as previously explained);
│  │  └─ libpq >=15.2,<16.0a0 , which cannot be installed (as previously explained);
│  ├─ qt-main 5.15.8 would require
│  │  ├─ alsa-lib >=1.2.8,<1.2.9.0a0 , which can be installed;
│  │  ├─ icu >=70.1,<71.0a0 , which can be installed;
│  │  ├─ krb5 >=1.20.1,<1.21.0a0 , which conflicts with any installable versions previously reported;
│  │  ├─ libjpeg-turbo >=2.1.5.1,<3.0a0 , which cannot be installed (as previously explained);
│  │  └─ libpq >=15.2,<16.0a0 , which cannot be installed (as previously explained);
│  ├─ qt-main 5.15.8 would require
│  │  ├─ alsa-lib >=1.2.9,<1.2.10.0a0 , which conflicts with any installable versions previously reported;
│  │  ├─ gst-plugins-base >=1.22.5,<1.23.0a0  with the potential options
│  │  │  ├─ gst-plugins-base 1.22.5, which can be installed;
│  │  │  ├─ gst-plugins-base [1.22.5|1.22.6|1.22.7|1.22.8|1.22.9] would require
│  │  │  │  └─ alsa-lib >=1.2.10,<1.3.0.0a0 , which conflicts with any installable versions previously reported;
│  │  │  └─ gst-plugins-base 1.22.9 would require
│  │  │     └─ alsa-lib >=1.2.11,<1.3.0a0 , which conflicts with any installable versions previously reported;
│  │  ├─ icu >=72.1,<73.0a0 , which conflicts with any installable versions previously reported;
│  │  ├─ libpq >=15.3,<16.0a0 , which cannot be installed (as previously explained);
│  │  ├─ libxcb >=1.15,<1.16.0a0 , which can be installed;
│  │  └─ openssl >=3.1.1,<4.0a0  with the potential options
│  │     ├─ openssl [3.1.3|3.1.4|3.1.5|3.1.6] conflicts with any installable versions previously reported;
│  │     ├─ openssl 3.1.1 conflicts with any installable versions previously reported;
│  │     ├─ openssl 3.1.2 conflicts with any installable versions previously reported;
│  │     ├─ openssl 3.2.0, which can be installed;
│  │     ├─ openssl [3.2.1|3.2.2], which can be installed;
│  │     ├─ openssl 3.3.0, which can be installed;
│  │     └─ openssl 3.3.1, which can be installed;
│  ├─ qt-main 5.15.8 would require
│  │  ├─ alsa-lib >=1.2.10,<1.3.0.0a0 , which conflicts with any installable versions previously reported;
│  │  ├─ icu >=73.2,<74.0a0 , which conflicts with any installable versions previously reported;
│  │  ├─ libjpeg-turbo >=3.0.0,<4.0a0 , which cannot be installed (as previously explained);
│  │  └─ openssl >=3.1.3,<4.0a0  with the potential options
│  │     ├─ openssl [3.1.3|3.1.4|3.1.5|3.1.6] conflicts with any installable versions previously reported;
│  │     ├─ openssl 3.2.0, which can be installed;
│  │     ├─ openssl [3.2.1|3.2.2], which can be installed;
│  │     ├─ openssl 3.3.0, which can be installed;
│  │     └─ openssl 3.3.1, which can be installed;
│  ├─ qt-main 5.15.8 would require
│  │  ├─ alsa-lib >=1.2.12,<1.3.0a0 , which conflicts with any installable versions previously reported;
│  │  ├─ icu >=73.2,<74.0a0 , which conflicts with any installable versions previously reported;
│  │  ├─ libjpeg-turbo >=3.0.0,<4.0a0 , which cannot be installed (as previously explained);
│  │  └─ openssl >=3.3.1,<4.0a0 , which can be installed;
│  ├─ qt-main 5.15.8 would require
│  │  ├─ alsa-lib >=1.2.10,<1.3.0.0a0 , which conflicts with any installable versions previously reported;
│  │  ├─ icu >=73.2,<74.0a0 , which conflicts with any installable versions previously reported;
│  │  ├─ libjpeg-turbo >=2.1.5.1,<3.0a0 , which cannot be installed (as previously explained);
│  │  └─ openssl >=3.1.2,<4.0a0  with the potential options
│  │     ├─ openssl [3.1.3|3.1.4|3.1.5|3.1.6] conflicts with any installable versions previously reported;
│  │     ├─ openssl 3.1.2 conflicts with any installable versions previously reported;
│  │     ├─ openssl 3.2.0, which can be installed;
│  │     ├─ openssl [3.2.1|3.2.2], which can be installed;
│  │     ├─ openssl 3.3.0, which can be installed;
│  │     └─ openssl 3.3.1, which can be installed;
│  └─ qt-main 5.15.8 would require
│     ├─ alsa-lib >=1.2.9,<1.2.10.0a0 , which conflicts with any installable versions previously reported;
│     ├─ icu >=72.1,<73.0a0 , which conflicts with any installable versions previously reported;
│     ├─ krb5 >=1.20.1,<1.21.0a0 , which conflicts with any installable versions previously reported;
│     ├─ libpq >=15.3,<16.0a0 , which cannot be installed (as previously explained);
│     ├─ libxcb >=1.15,<1.16.0a0 , which can be installed;
│     └─ openssl >=3.1.1,<4.0a0  with the potential options
│        ├─ openssl [3.1.3|3.1.4|3.1.5|3.1.6] conflicts with any installable versions previously reported;
│        ├─ openssl 3.1.1 conflicts with any installable versions previously reported;
│        ├─ openssl 3.1.2 conflicts with any installable versions previously reported;
│        ├─ openssl 3.2.0, which can be installed;
│        ├─ openssl [3.2.1|3.2.2], which can be installed;
│        ├─ openssl 3.3.0, which can be installed;
│        └─ openssl 3.3.1, which can be installed;
```

**Comment by ReimarBauer** [comment]
with `pyproj      3.6.1  py310h2e9f774_10  conda-forge     Cached` the error changed into 
`[Wed Oct 02 12:23:08.030625 2024] [wsgi:error] [pid 10148:tid 139789102163520] [remote 134.94.59.197:54244] ImportError: /lib/x86_64-linux-gnu/libssl.so.3: version `OPENSSL_3.2.0' not found (required by /home/mss-ascci/miniforge3/envs/mssenv/lib/python3.10/site-packages/pyproj/../../.././libcurl.so.4)`

**Comment by ReimarBauer** [comment]
Let's see if we can disable its trying for that version
```
>>> import ssl
>>> ssl.OPENSSL_VERSION
'OpenSSL 3.3.2 3 Sep 2024'
```

**Comment by ReimarBauer** [comment]
it looks outside the environment for a` /lib/x86_64-linux-gnu/libssl.so.3` that is completly wrong

**Comment by ReimarBauer** [comment]
https://github.com/conda-forge/curl-feedstock/issues/145

**Comment by ReimarBauer** [comment]
with ubuntu 24.04.1 the used libssl.so.3 is compatible to the recent curl 8.1.1 of conda-forge

**Comment by ReimarBauer** [comment]
this happens because mod_wsgi changes the LD_LIBRARY_PATH, which is not wanted. And which is something we can not solve on our site.
