### ISSUE TITLE
docs videos not visible on RTFD

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#2454]
something has changed, the tutorials are not  available on RTFD

**Comment by ReimarBauer** [comment]
- xstatic problem too
- copying does not work

```
[rtd-command-info] start-time: 2024-08-09T06:47:35.853416Z, end-time: 2024-08-09T06:50:23.310047Z, duration: 167, exit-code: 0
python -m sphinx -T -b html -d _build/doctrees -D language=en . $READTHEDOCS_OUTPUT/html
Error processing line 3 of /home/docs/checkouts/readthedocs.org/user_builds/mss/conda/stable/lib/python3.11/site-packages/XStatic-1.0.3-py3.10-nspkg.pth:

  Traceback (most recent call last):
    File "<frozen site>", line 195, in addpackage
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 570, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'
  
  
  WARNING: cannot copy image file '/home/docs/checkouts/readthedocs.org/user_builds/mss/checkouts/stable/docs/_static/mp4/tutorial_waypoints.mp4': /home/docs/checkouts/readthedocs.org/user_builds/mss/checkouts/stable/docs/_static/mp4/tutorial_waypoints.mp4 does not exist
copying images... [ 89%] _static/mp4/tutorial_hexagoncontrol.mp4
WARNING: cannot copy image file '/home/docs/checkouts/readthedocs.org/user_builds/mss/checkouts/stable/docs/_static/mp4/tutorial_hexagoncontrol.mp4': /home/docs/checkouts/readthedocs.org/user_builds/mss/checkouts/stable/docs/_static/mp4/tutorial_hexagoncontrol.mp4 does not exist
copying images... [ 90%] _static/mp4/tutorial_wms.mp4
WARNING: cannot copy image file '/home/docs/checkouts/readthedocs.org/user_builds/mss/checkouts/stable/docs/_static/mp4/tutorial_wms.mp4': /home/docs/checkouts/readthedocs.org/user_builds/mss/checkouts/stable/docs/_static/mp4/tutorial_wms.mp4 does not exist
copying images... [ 92%] _static/mp4/tutorial_kml.mp4
WARNING: cannot copy image file '/home/docs/checkouts/readthedocs.org/user_builds/mss/checkouts/stable/docs/_static/mp4/tutorial_kml.mp4': /home/docs/checkouts/readthedocs.org/user_builds/mss/checkouts/stable/docs/_static/mp4/tutorial_kml.mp4 does not exist
copying images... [ 94%] _static/mp4/tutorial_mscolab.mp4
WARNING: cannot copy image file '/home/docs/checkouts/readthedocs.org/user_builds/mss/checkouts/stable/docs/_static/mp4/tutorial_mscolab.mp4': /home/docs/checkouts/readthedocs.org/user_builds/mss/checkouts/stable/docs/_static/mp4/tutorial_mscolab.mp4 does not exist
copying images... [ 95%] _static/mp4/tutorial_views.mp4
WARNING: cannot copy image file '/home/docs/checkouts/readthedocs.org/user_builds/mss/checkouts/stable/docs/_static/mp4/tutorial_views.mp4': /home/docs/checkouts/readthedocs.org/user_builds/mss/checkouts/stable/docs/_static/mp4/tutorial_views.mp4 does not exist
copying images... [ 97%] _static/mp4/tutorial_performancesettings.mp4
WARNING: cannot copy image file '/home/docs/checkouts/readthedocs.org/user_builds/mss/checkouts/stable/docs/_static/mp4/tutorial_performancesettings.mp4': /home/docs/checkouts/readthedocs.org/user_builds/mss/checkouts/stable/docs/_static/mp4/tutorial_performancesettings.mp4 does not exist
copying images... [ 98%] _static/mp4/tutorial_remotesensing.mp4
WARNING: cannot copy image file '/home/docs/checkouts/readthedocs.org/user_builds/mss/checkouts/stable/docs/_static/mp4/tutorial_remotesensing.mp4': /home/docs/checkouts/readthedocs.org/user_builds/mss/checkouts/stable/docs/_static/mp4/tutorial_remotesensing.mp4 does not exist
copying images... [100%] _static/mp4/tutorial_satellitetrack.mp4
WARNING: cannot copy image file '/home/docs/checkouts/readthedocs.org/user_builds/mss/checkouts/stable/docs/_static/mp4/tutorial_satellitetrack.mp4': /home/docs/checkouts/readthedocs.org/user_builds/mss/checkouts/stable/docs/_static/mp4/tutorial_satellitetrack.mp4 does not exist


dumping search index in English (code: en)... done
dumping object inventory... done
Updating searchtools for Read the Docs search... build succeeded, 20 warnings.

The HTML pages are in ../_readthedocs/html.
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
```
