### ISSUE TITLE
problem in gcpoints_path

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#2456]
With some of our data I get

```
Fatal error in MSS 9.0.0 on Linux-6.5.0-10043-tuxedo-x86_64-with-glibc2.35
Python 3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:40:35) [GCC 12.3.0]

Please report bugs in MSS to https://github.com/Open-MSS/MSS

Information about the fatal error:

Traceback (most recent call last):
  File "/home/reimar/PycharmProjects/2024/rohit2p/MSS/mslib/msui/multiple_flightpath_dockwidget.py", line 764, in set_flag
    self.draw_inactive_operations()
  File "/home/reimar/PycharmProjects/2024/rohit2p/MSS/mslib/msui/multiple_flightpath_dockwidget.py", line 898, in draw_inactive_operations
    patch = MultipleFlightpath(self.view.map,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/reimar/PycharmProjects/2024/rohit2p/MSS/mslib/msui/multiple_flightpath_dockwidget.py", line 71, in __init__
    self.draw()
  File "/home/reimar/PycharmProjects/2024/rohit2p/MSS/mslib/msui/multiple_flightpath_dockwidget.py", line 110, in draw
    x, y = self.compute_xy(lon, lat)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/reimar/PycharmProjects/2024/rohit2p/MSS/mslib/msui/multiple_flightpath_dockwidget.py", line 78, in compute_xy
    x, y = self.map.gcpoints_path(lon, lat)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/reimar/PycharmProjects/2024/rohit2p/MSS/mslib/msui/mpl_map.py", line 723, in gcpoints_path
    assert len(lons) > 1
           ^^^^^^^^
```

**Comment by ReimarBauer** [comment]
we can import an ftml file without waypoints e.g.

```<?xml version="1.0" encoding="utf-8"?>
  <FlightTrack version="9.1.0">
    <ListOfWaypoints/>
  </FlightTrack>
```
