### ISSUE TITLE
unhandled crashes with mscolab verification shenanigangs

### ISSUE THREAD

**Issue by joernu76** [Open-MSS/MSS#2514]
Using the "verify-user-token" feature causes unexpected behaviour. it is suggested to disable this by default as a quick fix.

One error:

```test_authorized
ERROR: unexpected error: <class 'requests.exceptions.MissingSchema'> Invalid URL 'test_authorized': No scheme supplied. Perhaps you meant https://test_authorized?
```
looses the server URL in checking after an unsuccessful login attempt.

Another one

```
Traceback (most recent call last):
  File "/home/icg173/src/mss/mslib/msui/mscolab.py", line 1788, in set_active_op_id
    item.setFont(font)
RuntimeError: wrapped C/C++ object of type QListWidgetItem has been deleted
2024-09-07 19:05:40,314 (qt.excepthook:183): CRITICAL: MSS Version: 9.2.0
2024-09-07 19:05:40,315 (qt.excepthook:184): CRITICAL: Python Version: 3.10.11 | packaged by conda-forge | (main, May 10 2023, 18:58:44) [GCC 11.3.0]
2024-09-07 19:05:40,323 (qt.excepthook:185): CRITICAL: Platform: Linux-6.10.6+bpo-amd64-x86_64-with-glibc2.36 (('64bit', 'ELF'))
2024-09-07 19:05:40,323 (qt.excepthook:186): CRITICAL: Fatal error: Traceback (most recent call last):
  File "/home/icg173/src/mss/mslib/msui/mscolab.py", line 1788, in set_active_op_id
    item.setFont(font)
RuntimeError: wrapped C/C++ object of type QListWidgetItem has been deleted

Traceback (most recent call last):
  File "/home/icg173/src/mss/mslib/msui/mscolab.py", line 1735, in set_active_op_id
    logging.debug('set_active_op_id %s %s %s', item, item.op_id, self.active_op_id)
AttributeError: 'QListWidgetItem' object has no attribute 'op_id'
```
causes QT related crashes upon the forced logging out, which apparently doesn't clean up properly.

Also restarting the mscolab server (which triggers an unexpected logging out) causes several issues preventing MSUI from being properly used.

**Comment by ReimarBauer** [comment]
The default is to have it disabled, or?

**Comment by ReimarBauer** [comment]
When restarting the mscolab server it gets a random new secret. This invalidates all used tokens.

When diconnecting the internet the client can retry. A short disconnecting should not logout the client.

**Comment by joernu76** [comment]
> The default is to have it disabled, or?

Then we do not have a problem in stable. Good.

**Comment by joernu76** [comment]
The new fix should handle both of these issues. As this is not enabled by default, it need not be fixed in stable.
