### ISSUE TITLE
MSS crashes on point insertion

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#330]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/330) by Joern Ungermann (Bitbucket: [joernu76](https://bitbucket.org/joernu76), GitHub: [joernu76](https://github.com/joernu76)).**

----------------------------------------

```

Log file:
2018-04-23 21:17:25,770 (mss_qt.excepthook:169): MSS Version: 1.7.0
2018-04-23 21:17:25,771 (mss_qt.excepthook:170): Python Version: 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]
2018-04-23 21:17:25,771 (mss_qt.excepthook:171): Platform: Windows-7-6.1.7601-SP1 (('64bit', 'WindowsPE'))
2018-04-23 21:17:25,772 (mss_qt.excepthook:172): Fatal error: Traceback (most recent call last):
  File "C:\Users\icg173\Anaconda3\envs\mss-1.7.0-py3\lib\site-packages\mslib\msui\topview.py", line 260, in changeMapSection
    self.mpl.canvas.redraw_map(kwargs)
  File "C:\Users\icg173\Anaconda3\envs\mss-1.7.0-py3\lib\site-packages\mslib\msui\mpl_qtwidget.py", line 930, in redraw_map
    self.waypoints_interactor.update()
  File "C:\Users\icg173\Anaconda3\envs\mss-1.7.0-py3\lib\site-packages\mslib\msui\mpl_pathinteractor.py", line 910, in update
    self.waypoints_model)
  File "C:\Users\icg173\Anaconda3\envs\mss-1.7.0-py3\lib\site-packages\mslib\msui\mpl_pathinteractor.py", line 305, in update_from_WaypointsTableModel
    self.codes, self.vertices = list(zip(*pathdata))
  File "C:\Users\icg173\Anaconda3\envs\mss-1.7.0-py3\lib\site-packages\matplotlib\path.py", line 239, in codes
    self._update_values()
  File "C:\Users\icg173\Anaconda3\envs\mss-1.7.0-py3\lib\site-packages\matplotlib\path.py", line 204, in _update_values
    (self._codes is None or np.all(self._codes <= Path.LINETO))
TypeError: '<=' not supported between instances of 'tuple' and 'int'
```

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

Inserted intermediary variable to have a proped array before attribute access hit

Write to vertices attribute requires codes variable to be an array. In
the code, it is only a list at that point in time. The change performs
the conversion to array first so that vertices attribute access can
access codes as an array.

Fix issue #330
