### ISSUE TITLE
crash if "Remote sensing" is chosen

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#374]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/374) by Jens-Uwe Grooß (Bitbucket: [grooss](https://bitbucket.org/grooss), GitHub: [grooss](https://github.com/grooss)).**

----------------------------------------

If "Remote Sensing" is chosen on a top view panel (menu "select to open control"), the system freezes and gives the following error message (local path replaces by xx)

Fatal error in MSS 1.7.4 on Linux-4.15.0-38-generic-x86_64-with-debian-buster-sid
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0]

Please report bugs in MSS to https://bitbucket.org/wxmetvis/mss

Information about the fatal error:

Traceback (most recent call last):
  File "xx/miniconda3/lib/python3.6/site-packages/mslib/msui/topview.py", line 222, in openTool
    widget = rs.RemoteSensingControlWidget(view=self.mpl.canvas)
  File "xx/miniconda3/lib/python3.6/site-packages/mslib/msui/remotesensing_dockwidget.py", line 60, in __init__
    self.timescale = self.load.timescale()
  File "xx/miniconda3/lib/python3.6/site-packages/skyfield/iokit.py", line 272, in timescale
    leap_dates, leap_offsets = self('Leap_Second.dat')
  File "xx/miniconda3/lib/python3.6/site-packages/skyfield/iokit.py", line 184, in __call__
    expiration_date, data = parser(f)
  File "xx/miniconda3/lib/python3.6/site-packages/skyfield/iokit.py", line 369, in parse_leap_seconds
    dt = datetime.strptime(line, '#  File expires on %d %B %Y\n')
  File "xx/miniconda3/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "xx/miniconda3/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '#  File expires on 28 June 2019\n' does not match format '#  File expires on %d %B %Y\n'

**Comment by ReimarBauer** [comment]
**Original comment by Joern Ungermann (Bitbucket: [joernu76](https://bitbucket.org/joernu76), GitHub: [joernu76](https://github.com/joernu76)).**

----------------------------------------

Hi Jens-Uwe,

can this be the cause of the issue? 

https://github.com/skyfielders/python-skyfield/issues/217

I cannot replicate it with an English system.

**Comment by ReimarBauer** [comment]
**Original comment by Jens-Uwe Grooß (Bitbucket: [grooss](https://bitbucket.org/grooss), GitHub: [grooss](https://github.com/grooss)).**

----------------------------------------

How could I change to an English system/environment?

**Comment by ReimarBauer** [comment]
**Original comment by Joern Ungermann (Bitbucket: [joernu76](https://bitbucket.org/joernu76), GitHub: [joernu76](https://github.com/joernu76)).**

----------------------------------------

No expert here , mabye with the locale command?
https://www.cyberciti.biz/faq/how-to-set-locales-i18n-on-a-linux-unix/

**Comment by ReimarBauer** [comment]
**Original comment by Jens-Uwe Grooß (Bitbucket: [grooss](https://bitbucket.org/grooss), GitHub: [grooss](https://github.com/grooss)).**

----------------------------------------

yes, it is a language issue. 
Setting the environment variable LC_ALL=en_US solves the problem

**Comment by ReimarBauer** [comment]
**Original comment by Joern Ungermann (Bitbucket: [joernu76](https://bitbucket.org/joernu76), GitHub: [joernu76](https://github.com/joernu76)).**

----------------------------------------

skyfield will hopefully solve this internally. The issue is open and a solver has been assigned.
Interesting that we and they notice this issue rather close in time. The issue is open only since two weeks.

**Comment by ReimarBauer** [comment]
**Original comment by Joern Ungermann (Bitbucket: [joernu76](https://bitbucket.org/joernu76), GitHub: [joernu76](https://github.com/joernu76)).**

----------------------------------------

The issue has been solved upstream.
    https://github.com/skyfielders/python-skyfield/issues/217
but the fix seems not available in conda-forge, yet.

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

may be solved with the new version, related #383

**Comment by ReimarBauer** [comment]
**Original comment by Joern Ungermann (Bitbucket: [joernu76](https://bitbucket.org/joernu76), GitHub: [joernu76](https://github.com/joernu76)).**

----------------------------------------

Has been solved and *another* issues in skyfield has also been solved in the meantime.
This issue can be closed.

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

resolved by #bc4f3dc

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

duplicate of #383
