### ISSUE TITLE
fixate matplotlib to 3.0.2

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#408]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/408) by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

matplotlib 3.0.3 has  a color problem for the background color. It is not white

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

matplotlib 3.0.3 has in combination with basemap a color problem for the background color. It is not white

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

matplotlib version pinned to 3.0.2, fixes #408

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

Merged in ReimarBauer/mss/stable (pull request #642)

matplotlib version pinned to 3.0.2, fixes #408

**Comment by ReimarBauer** [comment]
**Original comment by Joern Ungermann (Bitbucket: [joernu76](https://bitbucket.org/joernu76), GitHub: [joernu76](https://github.com/joernu76)).**

----------------------------------------

MSS crashes with matplotlib 3.1.0 with unrelated\(?\) problem:  

```
CRITICAL: MSS Version: 1.8.0
CRITICAL: Python Version: 3.7.0 (default, Oct  9 2018, 10:31:47) 
[GCC 7.3.0]
CRITICAL: Platform: Linux-4.9.0-9-amd64-x86_64-with-debian-9.9 (('64bit', ''))
CRITICAL: Fatal error: Traceback (most recent call last):
  File "mss_pyui.py", line 433, in create_new_view
    view_window = topview.MSSTopViewWindow(model=self.active_flight_track)
  File "/home/icg173/src/mss/mslib/msui/topview.py", line 166, in __init__
    self.setupUi(self)
  File "/home/icg173/src/mss/mslib/msui/qt5/ui_topview_window.py", line 21, in setupUi
    self.mpl = MplTopViewWidget(self.centralwidget)
  File "/home/icg173/src/mss/mslib/msui/mpl_qtwidget.py", line 1180, in __init__
    sideview=False, parent=parent, canvas=MplTopViewCanvas())
  File "/home/icg173/src/mss/mslib/msui/mpl_qtwidget.py", line 481, in __init__
    self.navbar = NavigationToolbar(self.canvas, self, sideview)
  File "/home/icg173/src/mss/mslib/msui/mpl_qtwidget.py", line 235, in __init__
    super(NavigationToolbar, self).__init__(canvas, parent, coordinates)
  File "/home/icg173/anaconda3/lib/python3.7/site-packages/matplotlib/backends/backend_qt5.py", line 685, in __init__
    NavigationToolbar2.__init__(self, canvas)
  File "/home/icg173/anaconda3/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2627, in __init__
    self._init_toolbar()
  File "/home/icg173/src/mss/mslib/msui/mpl_qtwidget.py", line 429, in _init_toolbar
    self.buttons = {}
  File "/home/icg173/anaconda3/lib/python3.7/site-packages/matplotlib/cbook/deprecation.py", line 218, in __set__
    return super().__set__(instance, value)
AttributeError: can't set attribute
```

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

this is related to a deprecation.  May be we see that deprecation in the pinned version. Anyway that failure should not happen.
