### ISSUE TITLE
deprecation errors and warnings with current matplotlib versions

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#435]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/435) by Joern Ungermann (Bitbucket: [joernu76](https://bitbucket.org/joernu76), GitHub: [joernu76](https://github.com/joernu76)).**

----------------------------------------

There are several errors and warning occuring when starting mss with a current matplotlib version aside the visual issues. E.g.

‌

```
icg173@icg1705 ~/src/mss % python mss_pyui.py 
INFO: MSS Version: 1.8.1
INFO: Python Version: 3.7.0 (default, Oct  9 2018, 10:31:47) 
[GCC 7.3.0]
INFO: Platform: Linux-4.9.0-9-amd64-x86_64-with-debian-9.9 (('64bit', ''))
INFO: Launching user interface...
/home/icg173/src/mss/mslib/msui/mpl_qtwidget.py:429: MatplotlibDeprecationWarning: 
The buttons attribute was deprecated in Matplotlib 3.1 and will be removed in 3.3.
  self.buttons = {}
Traceback (most recent call last):
  File "mss_pyui.py", line 439, in create_new_view
    view_window = sideview.MSSSideViewWindow(model=self.active_flight_track)
  File "/home/icg173/src/mss/mslib/msui/sideview.py", line 246, in __init__
    self.setupUi(self)
  File "/home/icg173/src/mss/mslib/msui/qt5/ui_sideview_window.py", line 19, in setupUi
    self.mpl = MplSideViewWidget(self.centralwidget)
  File "/home/icg173/src/mss/mslib/msui/mpl_qtwidget.py", line 847, in __init__
    sideview=True, parent=parent, canvas=MplSideViewCanvas())
  File "/home/icg173/src/mss/mslib/msui/mpl_qtwidget.py", line 481, in __init__
    self.navbar = NavigationToolbar(self.canvas, self, sideview)
  File "/home/icg173/src/mss/mslib/msui/mpl_qtwidget.py", line 235, in __init__
    super(NavigationToolbar, self).__init__(canvas, parent, coordinates)
  File "/home/icg173/anaconda3/lib/python3.7/site-packages/matplotlib/backends/backend_qt5.py", line 685, in __init__
    NavigationToolbar2.__init__(self, canvas)
  File "/home/icg173/anaconda3/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2627, in __init__
    self._init_toolbar()
  File "/home/icg173/src/mss/mslib/msui/mpl_qtwidget.py", line 429, in _init_toolbar
    self.buttons = {}
  File "/home/icg173/anaconda3/lib/python3.7/site-packages/matplotlib/cbook/deprecation.py", line 218, in __set__
    return super().__set__(instance, value)
AttributeError: can't set attribute
```

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

Fixed several issues related with changes in matplotlib

Fix issue #435
