### ISSUE TITLE
TopView hang upon switching projection under certain conditions

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#445]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/445) by Joern Ungermann (Bitbucket: [joernu76](https://bitbucket.org/joernu76), GitHub: [joernu76](https://github.com/joernu76)).**

----------------------------------------

```
2019-08-22 14:16:41,937 (utils.get_projection_params:360): Identified CRS 'epsg:4326' as '{'basemap': {'epsg': '4326'}, 'bbox': 'degree'}'
2019-08-22 14:16:41,937 (topview.changeMapSection:282): switching to map section '00 global (cyl)' - '{'llcrnrlon': -180.0, 'llcrnrlat': -90.0, 'urcrnrlon': 180.0, 'urcrnrlat': 90.0, 'CRS': 'EPSG:4326', 'BBOX_UNITS': 'degree', 'epsg': '4326'}'
2019-08-22 14:16:41,941 (_base._update_title_position:2515): update_title_pos
2019-08-22 14:16:41,967 (mpl_qtwidget.redraw_map:937): redrawing map
2019-08-22 14:16:41,968 (mpl_map.update_with_coordinate_change:422): corner coordinates (lat/lon): ll(-90.00,-153.75), ur(75.65,3.69)
2019-08-22 14:16:41,968 (mss_qt.excepthook:172): MSS Version: 1.8.2
2019-08-22 14:16:41,969 (mss_qt.excepthook:173): Python Version: 3.7.0 (default, Oct  9 2018, 10:31:47)
[GCC 7.3.0]
2019-08-22 14:16:41,979 (mss_qt.excepthook:174): Platform: Linux-4.9.0-9-amd64-x86_64-with-debian-9.9 (('64bit', ''))
2019-08-22 14:16:41,979 (mss_qt.excepthook:175): Fatal error: Traceback (most recent call last):
  File "/home/icg173/anaconda3/envs/mss-1.8.2/lib/python3.7/site-packages/mslib/msui/topview.py", line 283, in changeMapSection
    self.mpl.canvas.redraw_map(kwargs)
  File "/home/icg173/anaconda3/envs/mss-1.8.2/lib/python3.7/site-packages/mslib/msui/mpl_qtwidget.py", line 946, in redraw_map
    self.map.update_with_coordinate_change(kwargs_update)
  File "/home/icg173/anaconda3/envs/mss-1.8.2/lib/python3.7/site-packages/mslib/msui/mpl_map.py", line 442, in update_with_coordinate_change
    self.map_coastlines.remove()
  File "/home/icg173/anaconda3/envs/mss-1.8.2/lib/python3.7/site-packages/matplotlib/artist.py", line 146, in remove
    self._remove_method(self)
ValueError: list.remove(x): x not in list
```

occurs in 1.8.2

Steps to reproduce:

* zoom out on a global cylindrical projection such that the continents can be seen multiple times horizontally.
* Switch to another projection

The TopView must be closed then, and a new one can be opened. to proceed with using MSS

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

Properly remove map_boundaries.

Also fix continent switching.

Fix issue #445
