### ISSUE TITLE
Fatal error in MSS after attempt to open "Remote sensing" overlay in Top View window

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#467]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/467) by Sören Johansson (Bitbucket: [soerenjohansson](https://bitbucket.org/soerenjohansson), ).**

----------------------------------------

After trying to open the Remote sensing overlay in the Top View window, I get a “Fatal error” with the following code in the command line:

‌

```
(base) C:\>conda activate mssenv

(mssenv) C:\>mss
INFO: MSS Version: 1.8.2
INFO: Python Version: 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
INFO: Platform: Windows-10-10.0.17763-SP0 (('64bit', 'WindowsPE'))
INFO: Launching user interface...
[#################################] 100% de421.bsp
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\mssenv\lib\urllib\request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\ProgramData\Anaconda3\envs\mssenv\lib\http\client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\ProgramData\Anaconda3\envs\mssenv\lib\http\client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\ProgramData\Anaconda3\envs\mssenv\lib\http\client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\ProgramData\Anaconda3\envs\mssenv\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\ProgramData\Anaconda3\envs\mssenv\lib\http\client.py", line 966, in send
    self.connect()
  File "C:\ProgramData\Anaconda3\envs\mssenv\lib\http\client.py", line 938, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\ProgramData\Anaconda3\envs\mssenv\lib\socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\ProgramData\Anaconda3\envs\mssenv\lib\socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\mssenv\lib\site-packages\skyfield\iokit.py", line 503, in download
    connection = urlopen(url)
  File "C:\ProgramData\Anaconda3\envs\mssenv\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\ProgramData\Anaconda3\envs\mssenv\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\ProgramData\Anaconda3\envs\mssenv\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:\ProgramData\Anaconda3\envs\mssenv\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\ProgramData\Anaconda3\envs\mssenv\lib\urllib\request.py", line 1345, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\ProgramData\Anaconda3\envs\mssenv\lib\urllib\request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\mssenv\lib\site-packages\mslib\msui\topview.py", line 243, in openTool
    widget = rs.RemoteSensingControlWidget(view=self.mpl.canvas)
  File "C:\ProgramData\Anaconda3\envs\mssenv\lib\site-packages\mslib\msui\remotesensing_dockwidget.py", line 60, in __init__
    self.timescale = self.load.timescale()
  File "C:\ProgramData\Anaconda3\envs\mssenv\lib\site-packages\skyfield\iokit.py", line 301, in timescale
    data = self('deltat.data')
  File "C:\ProgramData\Anaconda3\envs\mssenv\lib\site-packages\skyfield\iokit.py", line 191, in __call__
    download(url, path, self.verbose)
  File "C:\ProgramData\Anaconda3\envs\mssenv\lib\site-packages\skyfield\iokit.py", line 505, in download
    raise IOError('cannot get {0} because {1}'.format(url, e))
OSError: cannot get http://maia.usno.navy.mil/ser7/deltat.data because <urlopen error [Errno 11001] getaddrinfo failed>
CRITICAL: MSS Version: 1.8.2
CRITICAL: Python Version: 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
CRITICAL: Platform: Windows-10-10.0.17763-SP0 (('64bit', 'WindowsPE'))
CRITICAL: Fatal error: Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\mssenv\lib\urllib\request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\ProgramData\Anaconda3\envs\mssenv\lib\http\client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\ProgramData\Anaconda3\envs\mssenv\lib\http\client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\ProgramData\Anaconda3\envs\mssenv\lib\http\client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\ProgramData\Anaconda3\envs\mssenv\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\ProgramData\Anaconda3\envs\mssenv\lib\http\client.py", line 966, in send
    self.connect()
  File "C:\ProgramData\Anaconda3\envs\mssenv\lib\http\client.py", line 938, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\ProgramData\Anaconda3\envs\mssenv\lib\socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\ProgramData\Anaconda3\envs\mssenv\lib\socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\mssenv\lib\site-packages\skyfield\iokit.py", line 503, in download
    connection = urlopen(url)
  File "C:\ProgramData\Anaconda3\envs\mssenv\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\ProgramData\Anaconda3\envs\mssenv\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\ProgramData\Anaconda3\envs\mssenv\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:\ProgramData\Anaconda3\envs\mssenv\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\ProgramData\Anaconda3\envs\mssenv\lib\urllib\request.py", line 1345, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\ProgramData\Anaconda3\envs\mssenv\lib\urllib\request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\mssenv\lib\site-packages\mslib\msui\topview.py", line 243, in openTool
    widget = rs.RemoteSensingControlWidget(view=self.mpl.canvas)
  File "C:\ProgramData\Anaconda3\envs\mssenv\lib\site-packages\mslib\msui\remotesensing_dockwidget.py", line 60, in __init__
    self.timescale = self.load.timescale()
  File "C:\ProgramData\Anaconda3\envs\mssenv\lib\site-packages\skyfield\iokit.py", line 301, in timescale
    data = self('deltat.data')
  File "C:\ProgramData\Anaconda3\envs\mssenv\lib\site-packages\skyfield\iokit.py", line 191, in __call__
    download(url, path, self.verbose)
  File "C:\ProgramData\Anaconda3\envs\mssenv\lib\site-packages\skyfield\iokit.py", line 505, in download
    raise IOError('cannot get {0} because {1}'.format(url, e))
OSError: cannot get http://maia.usno.navy.mil/ser7/deltat.data because <urlopen error [Errno 11001] getaddrinfo failed>
```

The problem is not reproducable on another Windows PC with the same pyhton and mss version installed, so it is also likely that I did not configure everything in the proper way - but I don’t know what I could have missed.

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

We do use skyfield, and this has to fetch a deltat.data file.   
This file needs once fetched or copied to MSS\_CONFIG\_PATH

Please try if you can access it by your browser    
[http://maia.usno.navy.mil/ser7/deltat.data](http://maia.usno.navy.mil/ser7/deltat.data)

It looks like during the download of the file there was a internet connection failure.

‌

**Comment by ReimarBauer** [comment]
**Original comment by Sören Johansson (Bitbucket: [soerenjohansson](https://bitbucket.org/soerenjohansson), ).**

----------------------------------------

Thanks for your suggestions: I tried to connect to your link in my browser and it worked without a problem. 

I tried another attempt to open the Remote Sensing control panel after I started MSS as Windows administrator and then it worked. So I think the problem is that I installed Anaconda, and the MSS environment as Windows administrator, so I guess I cannot download the file to the folder the Remote Sensing control needs without administrator privileges. 

So my workaround was to create a new environment as “normal” user and now it works. Sorry for reporting this before I tried to fix everything I messed up in my system, but maybe someone else will have the same problem.

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

this is similiar to #431

**Comment by ReimarBauer** [comment]
**Original comment by Joern Ungermann (Bitbucket: [joernu76](https://bitbucket.org/joernu76), GitHub: [joernu76](https://github.com/joernu76)).**

----------------------------------------

yeah, this came up a couple of times. Annoying as hell. If somebody has a more stable way to compute sun/moon/venus positions, I’d have a look at that.

I personally have also intermittent errors, meaning that it crashes now and then works 10s later.

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

The crash happens likly because of urlopen had for a moment no access.  
[https://github.com/skyfielders/python-skyfield/blob/master/skyfield/iokit.py#L505](https://github.com/skyfielders/python-skyfield/blob/master/skyfield/iokit.py#L505)

The download to a path is at line 523.

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

Duplicate of #431.
