### ISSUE TITLE
non existing default config path fails on windows

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#49]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/49) by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

On a fresh installation without a common .config directory the start of mss fails
on windows

```
#!text

C:\Users\user\mss\staged-recipes\recipes\mss>mss
Traceback (most recent call last):
  File "C:\Users\user\Miniconda2\Scripts\mss-script.py", line 3, in <module>
    import mslib.msui.mss_pyui
  File "C:\Users\user\Miniconda2\lib\site-packages\mslib\msui\mss_pyui.py", li
ne 57, in <module>
    from mslib.msui import flighttrack as ft
  File "C:\Users\user\Miniconda2\lib\site-packages\mslib\msui\flighttrack.py",
 line 46, in <module>
    from mslib.mss_util import config_loader
  File "C:\Users\user\Miniconda2\lib\site-packages\mslib\mss_util.py", line 46
, in <module>
    from mslib.msui import wms_login_cache
  File "C:\Users\user\Miniconda2\lib\site-packages\mslib\msui\wms_login_cache.
py", line 36, in <module>
    os.mkdir(DEFAULT_CONFIG_PATH)
WindowsError: [Error 3] Das System kann den angegebenen Pfad nicht finden: 'C:\\
Users\\user\\.config\\mss'

C:\Users\user\mss\staged-recipes\recipes\mss>
```

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

Merged in ReimarBauer/mss (pull request #75)

check for ~/.config directory and if not present create it., fixes #49
