### ISSUE TITLE
ModuleNotFoundError: No module named 'jplephem.pck'

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#515]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/515) by Shawn Honomichl (Bitbucket: [Shawn](https://bitbucket.org/Shawn), GitHub: [Shawn](https://github.com/Shawn)).**

----------------------------------------

Did an update and attempted fresh install on another computer \(both macs\) of the mss and started getting the following python error that prevented the MSS from running: 

File "/Users/shawnh/miniconda3/envs/mssenv/bin/mss", line 7, in <module>  
from mslib.msui.mss\_pyui import main  
File "/Users/shawnh/miniconda3/envs/mssenv/lib/python3.7/site-packages/mslib/msui/mss\_pyui.py", line 73, in <module>  
from mslib.msui import topview  
File "/Users/shawnh/miniconda3/envs/mssenv/lib/python3.7/site-packages/mslib/msui/topview.py", line 41, in <module>  
from mslib.msui import remotesensing\_dockwidget as rs  
File "/Users/shawnh/miniconda3/envs/mssenv/lib/python3.7/site-packages/mslib/msui/remotesensing\_dockwidget.py", line 33, in <module>  
from skyfield.api import Loader, Topos, utc  
File "/Users/shawnh/miniconda3/envs/mssenv/lib/python3.7/site-packages/skyfield/api.py", line 14, in <module>  
from .planetarylib import PlanetaryConstants  
File "/Users/shawnh/miniconda3/envs/mssenv/lib/python3.7/site-packages/skyfield/planetarylib.py", line 5, in <module>  
from jplephem.pck import DAF, PCK  
ModuleNotFoundError: No module named 'jplephem.pck'

‌

Was able to get around the issue by force reinstalling jplephem…Likely an issue with the skyfield package.?.

-Shawn Honomichl

‌

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

The recipe has set a rule   
skyfield >=1.12

‌

I see on conda-forge now 1.16. released 9days ago, [https://anaconda.org/conda-forge/skyfield/files](https://anaconda.org/conda-forge/skyfield/files)

which version is on your system?

this looks like similiar to:

[https://github.com/conda-forge/skyfield-feedstock/issues/24](https://github.com/conda-forge/skyfield-feedstock/issues/24)

**Comment by ReimarBauer** [comment]
**Original comment by Shawn Honomichl (Bitbucket: [Shawn](https://bitbucket.org/Shawn), GitHub: [Shawn](https://github.com/Shawn)).**

----------------------------------------

I am also using version 1.16.

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

I looked up the recent jplehem builds  [https://github.com/conda-forge/jplephem-feedstock/pulls](https://github.com/conda-forge/jplephem-feedstock/pulls) doctests are failling, the pypi version is 2.12 but since 2.10 the conda build system finds errors.

**Comment by ReimarBauer** [comment]
**Original comment by Shawn Honomichl (Bitbucket: [Shawn](https://bitbucket.org/Shawn), GitHub: [Shawn](https://github.com/Shawn)).**

----------------------------------------

I was able to resolve the issue by force reinstalling jplephyem.

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

if I try to install manually `conda create -n pbenv jplephem`

I can reproduce the problem

‌

```
from jplephem.pck import DAF, PCK

Traceback (most recent call last):File "<stdin>", line 1, in <module>ModuleNotFoundError: No module named 'jplephem.pck
```

‌

but `pip install jplephem` `--upgrade` solves it

‌

‌

For the next mss release we have to get the package on conda-forge fixed first

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

added an issue to

[https://github.com/conda-forge/jplephem-feedstock/issues/17](https://github.com/conda-forge/jplephem-feedstock/issues/17)

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

we can now use jplephem>=2.12

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

We just created a new build of skyfield and I verified this in a new env   
[https://anaconda.org/conda-forge/skyfield/files](https://anaconda.org/conda-forge/skyfield/files)

‌

‌

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

fixed uptream by fixing jplephem and doing a releated skyfield build 

Thx to all involved!

https://github.com/conda-forge/jplephem-feedstock/issues/17
