### ISSUE TITLE
Missing Configuration file and Fatal error while using other configuration file.

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#547]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/547) by Vaibhav Mehra (Bitbucket: [Vaibhav Mehra](https://bitbucket.org/Vaibhav Mehra), ).**

----------------------------------------

I downloaded the stable version of mss from conda forge and tried load configuration under the section of file and it is opening an empty folder in front of me. Then I tried to open the config settings of the developing branch I have in the stable-downloaded mss and it is giving the following error.

‌

```
Fatal error in MSS 1.9.2. on Linux-5.0.0-38-generic-x86_64-with-debian-buster-sid
Python 3.7.6 | packaged by conda-forge | (default, Mar  5 2020, 15:27:18) 
[GCC 7.3.0]

Please report bugs in MSS to https://bitbucket.org/wxmetvis/mss

Information about the fatal error:

Traceback (most recent call last):
  File "/home/vaibhav/anaconda3/envs/comm/lib/python3.7/site-packages/mslib/msui/mss_pyui.py", line 597, in open_config_file
    self.add_plugins()
  File "/home/vaibhav/anaconda3/envs/comm/lib/python3.7/site-packages/mslib/msui/mss_pyui.py", line 289, in add_plugins
    dataset="filepicker_default", default=mss_default.filepicker_default)
  File "/home/vaibhav/anaconda3/envs/comm/lib/python3.7/site-packages/mslib/utils.py", line 114, in config_loader
    _fs = open_fs(_dirname)
  File "/home/vaibhav/anaconda3/envs/comm/lib/python3.7/site-packages/fs/opener/registry.py", line 226, in open_fs
    default_protocol=default_protocol,
  File "/home/vaibhav/anaconda3/envs/comm/lib/python3.7/site-packages/fs/opener/registry.py", line 187, in open
    open_fs = opener.open_fs(fs_url, parse_result, writeable, create, cwd)
  File "/home/vaibhav/anaconda3/envs/comm/lib/python3.7/site-packages/fs/opener/osfs.py", line 41, in open_fs
    osfs = OSFS(path, create=create)
  File "/home/vaibhav/.local/lib/python3.7/site-packages/fs/osfs.py", line 140, in __init__
    raise errors.CreateFailed(message)
fs.errors.CreateFailed: root path '/home/vaibhav/mss/home/vaibhav/config/mss' does not exist
```

‌

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

the path is the cause for the crash, it looks like a doubled valid path

\`/home/vaibhav/mss/home/vaibhav/config/mss\`

at least it should not crash

On current master develop

git rev-parse --verify HEAD  
8a26606f06402324e02b6547137e843f0f8103b1

I can’t reproduce it

‌

‌

‌

‌

‌

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

reopen if it happens again
