### ISSUE TITLE
test_sideview needs a review

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#581]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/581) by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

test\_sideview needs a review. Sometimes this happens

```
mslib/msui/_tests/test_sideview.py:180: AssertionError
 * Serving Flask app "mslib.index" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
PASSED [ 55%] * Serving Flask app "mslib.index" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
PASSED [ 55%]SKIPPED                         [ 55%]
Skipped: file(s) previously passed FLAKE8 checks
PASSED [ 56%]Traceback (most recent call last):
  File "/home/user/PycharmProjects/mss/mslib/msui/sideview.py", line 239, in verticalunitsclicked
    thermolib.pressure2flightlevel(self.sbPbot.value() * 100), "hft", unit))
  File "/home/user/PycharmProjects/mss/mslib/thermolib.py", line 850, in pressure2flightlevel
    raise ValueError("pressure to flight level conversion not "
ValueError: pressure to flight level conversion not implemented for z > 71km (p ~ 4 Pa)
```

‌

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

can't reproduce
