### ISSUE TITLE
from matplotlib.cbook import dedent

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#593]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/593) by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

basemap / matplotlib problem 

‌

with basemap-1.2.1 and matplotlib-3.3.2 

I get for a fresh build 

‌

‌

```
 mss -h
Traceback (most recent call last):
  File "/home/user/miniconda3/conda-bld/mss_1604849842252/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/mss", line 7, in <module>
    from mslib.msui.mss_pyui import main
  File "/home/user/miniconda3/conda-bld/mss_1604849842252/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.8/site-packages/mslib/msui/mss_pyui.py", line 48, in <module>
    from mslib.msui.mss_qt import ui_mainwindow as ui
  File "/home/user/miniconda3/conda-bld/mss_1604849842252/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.8/site-packages/mslib/msui/mss_qt.py", line 178, in <module>
    globals()[mod] = importlib.import_module("mslib.msui.qt5." + mod)
  File "/home/user/miniconda3/conda-bld/mss_1604849842252/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/user/miniconda3/conda-bld/mss_1604849842252/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.8/site-packages/mslib/msui/qt5/ui_sideview_window.py", line 66, in <module>
    from mslib.msui.mpl_qtwidget import MplSideViewWidget
  File "/home/user/miniconda3/conda-bld/mss_1604849842252/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.8/site-packages/mslib/msui/mpl_qtwidget.py", line 49, in <module>
    from mslib.msui import mpl_map
  File "/home/user/miniconda3/conda-bld/mss_1604849842252/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.8/site-packages/mslib/msui/mpl_map.py", line 40, in <module>
    import mpl_toolkits.basemap as basemap
  File "/home/user/miniconda3/conda-bld/mss_1604849842252/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.8/site-packages/mpl_toolkits/basemap/__init__.py", line 26, in <module>
    from matplotlib.cbook import dedent
ImportError: cannot import name 'dedent' from 'matplotlib.cbook' (/home/user/miniconda3/conda-bld/mss_1604849842252
```

‌

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

Also missing in that combination

```
basemap                   1.2.2            py39h523bb60_3    conda-forge

matplotlib                3.3.2            py39hde42818_1    conda-forge
```

‌

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

looked into basemap code

‌

‌

```
try:
    from inspect import cleandoc as dedent
except ImportError:
    # Deprecated as of version 3.1. Not quite the same
    # as textwrap.dedent.
    from matplotlib.cbook import dedent
```

‌

trying with installing typing\_inspect

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

Part of the solution

[https://github.com/conda-forge/basemap-feedstock/issues/71](https://github.com/conda-forge/basemap-feedstock/issues/71)  

Looking now at for the same reason on

```
from .proj import Proj
```

this will likly need a PR and a new build

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

this is in basemap-1.2.2-3 solved.

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

We get   
basemap                   1.2.1            py37hd1be537\_2    conda-forge

but seem not to be able to update 

```

mamba install basemap=1.2.2=py37h79d9017_3
Problem: package basemap-1.2.2-py37h79d9017_3 requires proj >=7.2.0,<7.2.1.0a0, but none of the providers can be installed
```

‌

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

a clean build environment solves this
