### ISSUE TITLE
problem with update_with_coordinate_change

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#609]
Happened when I zoom into a highlevel detail on topview. 

![detail_zoom](https://user-images.githubusercontent.com/278728/101779723-f06ce900-3af5-11eb-9393-3b20a440f048.png)

 
```
please report bugs in MSS to https://github.com/Open-MSS/MSS

Information about the fatal error:

Traceback (most recent call last):
  File "/home/user/miniconda3/envs/mss2/lib/python3.8/site-packages/mslib/msui/mpl_qtwidget.py", line 1155, in historyEvent
    self.canvas.redraw_map()
  File "/home/user/miniconda3/envs/mss2/lib/python3.8/site-packages/mslib/msui/mpl_qtwidget.py", line 932, in redraw_map
    self.map.update_with_coordinate_change(kwargs_update)
  File "/home/user/miniconda3/envs/mss2/lib/python3.8/site-packages/mslib/msui/mpl_map.py", line 429, in update_with_coordinate_change
    self.map_coastlines.remove()
  File "/home/user/miniconda3/envs/mss2/lib/python3.8/site-packages/matplotlib/artist.py", line 134, in remove
    self._remove_method(self)
ValueError: list.remove(x): x not in list

```
As a workaround if you were using the colab feature:
When that happen e.g. disconnect and reconnect again. You get back what you did until the crash.

**Comment by ReimarBauer** [comment]
```
  File "/home/user/PycharmProjects/mss/mslib/msui/mpl_qtwidget.py", line 296, in _zoom_pan_handler
    super(NavigationToolbar, self)._zoom_pan_handler(event)
  File "/home/user/miniconda3/envs/mssdev/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 3019, in _zoom_pan_handler
    self.release_zoom(event)
  File "/home/user/PycharmProjects/mss/mslib/msui/mpl_qtwidget.py", line 355, in release_zoom
    self.canvas.redraw_map()
  File "/home/user/PycharmProjects/mss/mslib/msui/mpl_qtwidget.py", line 932, in redraw_map
    self.map.update_with_coordinate_change(kwargs_update)
  File "/home/user/PycharmProjects/mss/mslib/msui/mpl_map.py", line 464, in update_with_coordinate_change
    self.__init__(**self.kwargs)
  File "/home/user/PycharmProjects/mss/mslib/msui/mpl_map.py", line 107, in __init__
    self.map_coastlines = self.drawcoastlines(zorder=3)
  File "/home/user/miniconda3/envs/mssdev/lib/python3.8/site-packages/mpl_toolkits/basemap/__init__.py", line 1855, in drawcoastlines
    coastlines = LineCollection(self.coastsegs,antialiaseds=(antialiased,))
  File "/home/user/miniconda3/envs/mssdev/lib/python3.8/site-packages/matplotlib/collections.py", line 1393, in __init__
    self.set_segments(segments)
  File "/home/user/miniconda3/envs/mssdev/lib/python3.8/site-packages/matplotlib/collections.py", line 1408, in set_segments
    self._paths = [mpath.Path(_seg) for _seg in _segments]
  File "/home/user/miniconda3/envs/mssdev/lib/python3.8/site-packages/matplotlib/collections.py", line 1408, in <listcomp>
    self._paths = [mpath.Path(_seg) for _seg in _segments]
  File "/home/user/miniconda3/envs/mssdev/lib/python3.8/site-packages/matplotlib/path.py", line 132, in __init__
    cbook._check_shape((None, 2), vertices=vertices)
  File "/home/user/miniconda3/envs/mssdev/lib/python3.8/site-packages/matplotlib/cbook/__init__.py", line 2303, in _check_shape
    raise ValueError(
ValueError: 'vertices' must be 2D with shape (M, 2). Your input has shape (0,).
```

**Comment by Marilyth** [comment]
Seems to be happening because it is trying to draw a coastline where none is.
I am not sure if this isn't something Basemap should handle themselves though.
I will fix this for the time being.
