### ISSUE TITLE
after login on yourmss error shown on terminal

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#617]
After a login on yourmss I see an error message processed by the client. 
The login seems to have succeeded, I can continue with the session.

`Fatal error in MSS 2.0.0. on Linux-4.15.0-129-generic-x86_64-with-glibc2.10
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0]

Please report bugs in MSS to https://github.com/Open-MSS/MSS

Information about the fatal error:

Traceback (most recent call last):
  File "/home/user/PycharmProjects/students/marilyth/MSS/mslib/msui/mscolab.py", line 549, in authorize
    self.after_authorize(emailid, r)
  File "/home/user/PycharmProjects/students/marilyth/MSS/mslib/msui/mscolab.py", line 561, in after_authorize
    self.conn = sc.ConnectionManager(self.token, user=self.user, mscolab_server_url=self.mscolab_server_url)
  File "/home/user/PycharmProjects/students/marilyth/MSS/mslib/msui/socket_control.py", line 54, in __init__
    self.sio.connect(self.mscolab_server_url)
  File "/home/user/miniconda3/envs/mssdev/lib/python3.8/site-packages/socketio/client.py", line 284, in connect
    raise exceptions.ConnectionError(exc.args[0]) from None
socketio.exceptions.ConnectionError: Unexpected response from server`

**Comment by ReimarBauer** [comment]
this happens also in the stable master branch and with the builtin server.

**Comment by ReimarBauer** [comment]
We have a strong dependency to python-engineio>=3.13.2 <4
We do have a lot failing tests with 4.0.0 of  python-engineio

pytest -k mscolab_project fails immediatly

**Comment by ReimarBauer** [comment]
We need a fix in our meta.yaml 
python-engineio>=3.13.2 <4
flask-socketio >=4.3.1 <5
python-socketio >=4.6.0<5

**Comment by ReimarBauer** [comment]
I try to do a fast fix of these dependencies with a 3.9 build, increasing the build number 
https://github.com/conda-forge/mss-feedstock/pull/85
