### ISSUE TITLE
KeyError: 'PROJ_LIB'

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#630]
it seems that we don'r have the patch available if we have installed the developer environment by
```
$ conda create -n mssdev python=3 mamba
$ conda activate mssdev
(mssdev)$ mamba install mss --only-deps
```
This shows up as failure when e.g. the server is started now
```
WARNING:root:Couldn't import mscolab_settings (ImportError:'No module named 'mscolab_settings''), using dummy config.
Traceback (most recent call last):
  File "/home/user/PycharmProjects/mss/mslib/mscolab/server.py", line 44, in <module>
    from mslib.utils import conditional_decorator
  File "/home/user/PycharmProjects/mss/mslib/utils.py", line 42, in <module>
    import mpl_toolkits.basemap.pyproj as pyproj
  File "/home/user/miniconda3/envs/mssdev2/lib/python3.9/site-packages/mpl_toolkits/basemap/__init__.py", line 152, in <module>
    pyproj_datadir = os.environ['PROJ_LIB']
  File "/home/user/miniconda3/envs/mssdev2/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'PROJ_LIB'
```

**Comment by ReimarBauer** [comment]
setting this var seems to be all needed
```(mssdev)$ export PROJ_LIB=$CONDA_PREFIX/share/proj```

**Comment by ReimarBauer** [comment]
that's maybe also a difference for mamba?

**Comment by ReimarBauer** [comment]
verified
(mssdev)$ conda install mss --only-deps

creates the env var but replaced by mamba not

But I also found an easy solution, The env var is enabled on restarting the env.

```
conda deactivate
conda activate mssdev
```

**Comment by ReimarBauer** [comment]
documentation fixed and upwards reported
