### ISSUE TITLE
crash in mscolab on development

### ISSUE THREAD

**Issue by joernu76** [Open-MSS/MSS#727]
Was just playing around with a fresh mscolab server. 
Created a user, logged in, double-clicked the new project/flight track
```
INFO: Emitting event "start" [/]
INFO: Sending packet MESSAGE data 2["start",{"token":"eyJhbGciOiJIUzUxMiIsImlhdCI6MTYxNjE2ODQ1MSwiZXhwIjoxNjE3MDMyNDUxfQ.eyJpZCI6MX0.iaIlAyxnNEgIJZvXYEAnR65NqHxUaOJK5yOuW5tmo7d72aVAHIPA2_5Ub-sMrOwDm9_jlXxpAqIX9CtonFzdEw"}]
INFO: Received packet PONG data None
INFO: Sending polling GET request to http://localhost:8083/socket.io/?transport=polling&EIO=3&sid=858ea42dac6044c7a3cba6e2b5be60f4
INFO: Emitting event "add-user-to-room" [/]
INFO: Sending packet MESSAGE data 2["add-user-to-room",{"p_id":1,"token":"eyJhbGciOiJIUzUxMiIsImlhdCI6MTYxNjE2ODQ1MSwiZXhwIjoxNjE3MDMyNDUxfQ.eyJpZCI6MX0.iaIlAyxnNEgIJZvXYEAnR65NqHxUaOJK5yOuW5tmo7d72aVAHIPA2_5Ub-sMrOwDm9_jlXxpAqIX9CtonFzdEw"}]
Traceback (most recent call last):
  File "/home/icg173/src/mss/mslib/msui/mscolab.py", line 654, in set_active_pid
    self.load_wps_from_server()
  File "/home/icg173/src/mss/mslib/msui/mscolab.py", line 706, in load_wps_from_server
    xml_content = self.request_wps_from_server()
  File "/home/icg173/src/mss/mslib/msui/mscolab.py", line 700, in request_wps_from_server
    xml_content = json.loads(r.text)["content"]
  File "/opt/anaconda3/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/opt/anaconda3/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/anaconda3/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
CRITICAL: MSS Version: 2.0.1.
CRITICAL: Python Version: 3.8.6 | packaged by conda-forge | (default, Dec 26 2020, 05:05:16) 
[GCC 9.3.0]
CRITICAL: Platform: Linux-5.10.0-4-amd64-x86_64-with-glibc2.10 (('64bit', 'ELF'))
CRITICAL: Fatal error: Traceback (most recent call last):
  File "/home/icg173/src/mss/mslib/msui/mscolab.py", line 654, in set_active_pid
    self.load_wps_from_server()
  File "/home/icg173/src/mss/mslib/msui/mscolab.py", line 706, in load_wps_from_server
    xml_content = self.request_wps_from_server()
  File "/home/icg173/src/mss/mslib/msui/mscolab.py", line 700, in request_wps_from_server
    xml_content = json.loads(r.text)["content"]
  File "/opt/anaconda3/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/opt/anaconda3/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/anaconda3/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by ReimarBauer** [comment]
Hi @joernu76  
I do have problems to reproduce your error. The steps I did:
- python mslib/mscolab/mscolab.py  db --init
- python mslib/mscolab/server.py
- connected the url
- created user / logged in
- added project
- double clicked project
- selected topview

**Comment by joernu76** [comment]
I didn't try to replicate it, but it crashed already with the double-click. 
I tried to replicate now but couldn't.
Would something I did before locally influence this? The error seems related with getting the "fresh" flightpath data from the mscolab server.

**Comment by ReimarBauer** [comment]
Our testframework did what you've done manually several times a day.

I can only guess now. I assume you lost the connection to the server and this was not indicated.

To investigate this further first a test for several connection states is needed.

**Comment by joernu76** [comment]
Shouldn't happen in any case. Can one simply catch the Exception in the code at that place to handle that more gracefully?
A full client crash is not what we want in any case.

**Comment by ReimarBauer** [comment]
First is to have a test which can trigger that. That gives a better understanding what is needed or could be done. I look into this.

**Comment by joernu76** [comment]
I was using 2.0.0 instead of 2.0.1 because I was not delivered the most recent release by conda.
