### ISSUE TITLE
Requesting problematic layer gives strange error message

### ISSUE THREAD

**Issue by joernu76** [Open-MSS/MSS#770]
Requesting the "DYN wind barbs" layer from the SouthTrac server on current develop gives a strange error message:
`ERROR:
<class 'requests.exceptions.HTTPError'>
404 Client Error: Not Found for url: https://forecast.fz-juelich.de/index`

LOG:
```
2021-04-09 11:35:42,795 (wms_control.retrieve_image:1257): crs=EPSG:4326, path=None
2021-04-09 11:35:42,796 (wms_control.retrieve_image:1258): init_time=2019-11-27T12:00:00Z, valid_time=2019-11-27T12:00:00Z
2021-04-09 11:35:42,796 (wms_control.retrieve_image:1259): level=6.25
[redacted]
2021-04-09 11:35:43,330 (wms_control.process_map:299): MapPrefetcher Exception <class 'requests.exceptions.HTTPError'> - 404 Client Error: Not Found for /index.
2021-04-09 11:35:43,331 (wms_control.display_exception:643): NoneType: None

2021-04-09 11:36:59,463 (wms_control.service_cache:1388): servicing cache...
2021-04-09 11:36:59,566 (wms_control.service_cache:1419): cache has been cleaned (0 files removed).
```
I will investigate on the backend, but that the frontend contains an "index" in the error message is strange.

**Comment by joernu76** [comment]
@ReimarBauer 
Der Flask-Server zeigt das hier:
```
ERROR: Unexpected error: <class 'AttributeError'>: module 'mslib.mswms.utils' has no attribute 'convert_to'

ERROR: Traceback (most recent call last):
  File "/home/mss-southtrac/miniconda3/envs/southtrac/lib/python3.9/site-packages/mslib/mswms/wms.py", line 523, in application
    return_data, return_format = server.produce_plot(query, request_type)
  File "/home/mss-southtrac/miniconda3/envs/southtrac/lib/python3.9/site-packages/mslib/mswms/wms.py", line 427, in produce_plot
    image = plot_driver.plot()
  File "/home/mss-southtrac/miniconda3/envs/southtrac/lib/python3.9/site-packages/mslib/mswms/mss_plot_driver.py", line 637, in plot
    image = self.plot_object.plot_hsection(data,
  File "/home/mss-southtrac/miniconda3/envs/southtrac/lib/python3.9/site-packages/mslib/mswms/mpl_hsec.py", line 244, in plot_hsection
    self._prepare_datafields()
  File "/home/mss-southtrac/SOUTHTRAC/config/plots3.py", line 67, in _prepare_datafields
    utils.convert_to(
AttributeError: module 'mslib.mswms.utils' has no attribute 'convert_to'

INFO: 127.0.0.1 - - [09/Apr/2021 12:53:53] "GET /?service=WMS&request=GetMap&layers=gwfc.HS_BarbsC&styles=&width=353&height=176&srs=EPSG%3A4326&format=image%2Fpng&transparent=FALSE&bgcolor=0xFFFFFF&exceptions=application%2Fvnd.ogc.se_xml&bbox=-180.0%2C-90.0%2C180.0%2C90.0&time=2019-11-27T12%3A00%3A00Z&dim_init_time=2019-11-27T12%3A00%3A00Z&elevation=0.0 HTTP/1.1" 307 -
INFO: 127.0.0.1 - - [09/Apr/2021 12:53:53] "GET /index HTTP/1.1" 200 -
```
Der Apache ist wie immer stumm. Das muss sich mal ändern!
Im Frontend würde ich aber eine Service Exception erwarten, keinen index not found error???

**Comment by joernu76** [comment]
Ah, deswegen:
```
    except Exception as ex:
        error_message = "{}: {}\n".format(type(ex), ex)
        logging.error("Unexpected error: %s", error_message)
        logging.error("%s", traceback.format_exc())
        return redirect('/index', 307)
```
Warum macht der Server bei einem unerwarteten den redirect auf /index???

**Comment by joernu76** [comment]
This change causes the "problem":
```
 (e) base  ~  src  mss  git show f27929dbb mslib/mswms/wms.py                                                                                                 develop 
commit f27929dbbc40d87c7055b41b250dc73889452d71
Author: Reimar Bauer <rb.proj@gmail.com>
Date:   Thu Sep 24 12:00:08 2020 +0200

    moved redirect to index at the end of the query check

diff --git a/mslib/mswms/wms.py b/mslib/mswms/wms.py
index 540293c9..f215f616 100644
--- a/mslib/mswms/wms.py
+++ b/mslib/mswms/wms.py
@@ -500,9 +500,6 @@ server = WMSServer()
 @app.route('/')
 @conditional_decorator(auth.login_required, mss_wms_settings.__dict__.get('enable_basic_http_authentication', False))
 def application():
-    if request.query_string == b'':
-        res = redirect("index", 307)
-        return res
     try:
         # Request info
         query = request.args
@@ -538,10 +535,4 @@ def application():
     except Exception as ex:
         error_message = "{}: {}\n".format(type(ex), ex)
         logging.error("Unexpected error: %s", error_message)
-        error_message = error_message.encode("utf-8")
-
-        response_headers = [('Content-type', 'text/plain'), ('Content-Length', str(len(error_message)))]
-        res = make_response(error_message, 404)
-        for response_header in response_headers:
-            res.headers[response_header[0]] = response_header[1]
-        return res
+        return redirect('/index', 307)
```

In case of an unknown Server Error, we may not want to display internal stuff to the user, but we should indicate that it *is* an internal server problem and not redirect to index.

**Comment by ReimarBauer** [comment]
Wait for 2.0.3 :)

unfortunately there was yesterday no build for py 3.9

I guess it is still needs a similar fix

**Comment by joernu76** [comment]
The problematic exception handling is just as this in current stable *and* develop, so how will 2.0.3 change this?

I do not fully understand the intent of f27929dbb though. It certainly interferes with the core functionality of client-server communication.

**Comment by ReimarBauer** [comment]
the redirect was removed. that was a mistake.  We destinguish between call with parameters and without. 

I agree to add an error message back
