### ISSUE TITLE
disable retrieve on no layer 

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#777]
![block_retrieve](https://user-images.githubusercontent.com/278728/114302120-f5ec3700-9ac7-11eb-9275-1e04f622c4ce.png)

because of retrieve can't use a server it crashes by
```
Fatal error in MSS 2.0.3. on Linux-4.15.0-140-generic-x86_64-with-glibc2.27
Python 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:46) 
[GCC 9.3.0]

Please report bugs in MSS to https://github.com/Open-MSS/MSS

Information about the fatal error:

Traceback (most recent call last):
  File "/home/user/PycharmProjects/mss/mslib/msui/wms_control.py", line 538, in get_all_maps
    self.get_map(self.multilayers.get_active_layers())
  File "/home/user/PycharmProjects/mss/mslib/msui/wms_control.py", line 1577, in get_map
    wms = self.multilayers.layers[layer.wms_name]["wms"]
AttributeError: 'NoneType' object has no attribute 'wms_name'
```

Somehow I got the UI to enable that button. Currently I try to reproduce this, so that I can describe this path.

**Comment by ReimarBauer** [comment]
It gets enabled, when once a layer got unselected and next get capabilities is clicked
![no_layer_retrieve_on](https://user-images.githubusercontent.com/278728/114302595-ff769e80-9ac9-11eb-8b98-a20baab6de4e.gif)
