### ISSUE TITLE
SCRIPT_NAME needs better documentations for other web servers than apache2

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#823]
```
Fatal error in MSS 3.0.0. on Linux-4.15.0-142-generic-x86_64-with-glibc2.27
Python 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:46) 
[GCC 9.3.0]

Please report bugs in MSS to https://github.com/Open-MSS/MSS

Information about the fatal error:

Traceback (most recent call last):
  File "/home/user/miniconda3/envs/mssenv/lib/python3.9/site-packages/mslib/msui/mscolab.py", line 551, in authorize
    self.after_authorize(emailid, r)
  File "/home/user/miniconda3/envs/mssenv/lib/python3.9/site-packages/mslib/msui/mscolab.py", line 570, in after_authorize
    self.conn = sc.ConnectionManager(self.token, user=self.user, mscolab_server_url=self.mscolab_server_url)
  File "/home/user/miniconda3/envs/mssenv/lib/python3.9/site-packages/mslib/msui/socket_control.py", line 54, in __init__
    self.sio.connect(self.mscolab_server_url)
  File "/home/user/miniconda3/envs/mssenv/lib/python3.9/site-packages/socketio/client.py", line 286, in connect
    six.raise_from(exceptions.ConnectionError(exc.args[0]), None)
  File "<string>", line 3, in raise_from
socketio.exceptions.ConnectionError: Unexpected status code 500 in server response
```

**Comment by ReimarBauer** [comment]
Need first to investigate the proxy script_name setup
