### ISSUE TITLE
PathInteractors not properly deleted when View is closed

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#91]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/91) by Joern Ungermann (Bitbucket: [joernu76](https://bitbucket.org/joernu76), GitHub: [joernu76](https://github.com/joernu76)).**

----------------------------------------

When a Side- or TopView is closed the associated PathInteractor lingers and throws nasty errors to the console.
The error can be reproduced most easily by creating a Top&SideView, deleting the SideView and then moving a Waypoint.
Result:

```
#!log


Traceback (most recent call last):
  File "C:\Users\icg173\src\mss.perf2\mslib\msui\mpl_pathinteractor.py", line 771, in qt_data_changed_listener
    self.redraw_figure()
  File "C:\Users\icg173\src\mss.perf2\mslib\msui\mpl_pathinteractor.py", line 693, in redraw_figure
    self.redraw_path()
  File "C:\Users\icg173\src\mss.perf2\mslib\msui\mpl_pathinteractor.py", line 608, in redraw_path
    self.canvas.blit(self.ax.bbox)
  File "C:\Users\icg173\Anaconda\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 200, in blit
    self.repaint(l, self.renderer.height-t, w, h)
RuntimeError: wrapped C/C++ object of type MplSideViewCanvas has been deleted

```

The PathInteractor is connected to the WayPointTable using a QT connect command. Disconnecting this might do the trick... I could not easily find out how this might be achieved from the perspective of the Class that actually knows that it is being closed.

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

Fixes issue #91
