### ISSUE TITLE
 Logging error on windows with default config

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#928]
A fresh installed windows 10 mss 3.0.2 shows on the terminal by starting mss using the default configuration
```
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\user\Miniconda3\envs\mssdev\lib\logging\__init__.py", line 1083, in emit
    self.flush()
  File "C:\Users\user\Miniconda3\envs\mssdev\lib\logging\__init__.py", line 1063, in flush
    self.stream.flush()
OSError: [Errno 22] Invalid argument
Call stack:
  File "C:\Users\user\Miniconda3\envs\mssdev\Scripts\mss-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\user\Miniconda3\envs\mssdev\lib\site-packages\mslib\msui\mss_pyui.py", line 792, in main
    mainwindow = MSSMainWindow()
  File "C:\Users\user\Miniconda3\envs\mssdev\lib\site-packages\mslib\msui\mss_pyui.py", line 194, in __init__
    self.last_save_directory = config_loader(dataset="data_dir")
  File "C:\Users\user\Miniconda3\envs\mssdev\lib\site-packages\mslib\utils.py", line 154, in config_loader
    logging.info(
Message: 'Default MSS configuration in place, no user settings, see http://mss.rtfd.io/
```

**Comment by ReimarBauer** [comment]
I tried the installed build of the proposed PR on a windows 10.

**Comment by ReimarBauer** [comment]
We need more details
