### ISSUE TITLE
windows Locking problem in git

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#989]
```
Exception in thread Thread-65:
Traceback (most recent call last):
  File "C:\Users\user\Miniconda3\envs\mssdev\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\user\Miniconda3\envs\mssdev\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\Miniconda3\envs\mssdev\lib\site-packages\socketio\server.py", line 685, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "C:\Users\user\Miniconda3\envs\mssdev\lib\site-packages\socketio\server.py", line 714, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "C:\Users\user\Miniconda3\envs\mssdev\lib\site-packages\flask_socketio\__init__.py", line 283, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "C:\Users\user\Miniconda3\envs\mssdev\lib\site-packages\flask_socketio\__init__.py", line 716, in _handle_event
    ret = handler(*args)
  File "C:\Users\user\workspace\MSS\mslib\mscolab\sockets_manager.py", line 207, in handle_file_save
    if perm and self.fm.save_file(int(p_id), content, user, comment):
  File "C:\Users\user\workspace\MSS\mslib\mscolab\file_manager.py", line 208, in save_file
    cm = repo.index.commit("committing changes")
  File "C:\Users\user\Miniconda3\envs\mssdev\lib\site-packages\git\index\base.py", line 951, in commit
    rval = Commit.create_from_tree(self.repo, tree, message, parent_commits,
  File "C:\Users\user\Miniconda3\envs\mssdev\lib\site-packages\git\objects\commit.py", line 420, in create_from_tree
    repo.head.set_commit(new_commit, logmsg=message)
  File "C:\Users\user\Miniconda3\envs\mssdev\lib\site-packages\git\refs\symbolic.py", line 232, in set_commit
    self.set_object(commit, logmsg)
  File "C:\Users\user\Miniconda3\envs\mssdev\lib\site-packages\git\refs\symbolic.py", line 261, in set_object
    return self._get_reference().set_object(object, logmsg)
  File "C:\Users\user\Miniconda3\envs\mssdev\lib\site-packages\git\refs\reference.py", line 79, in set_object
    self.repo.head.log_append(oldbinsha, logmsg)
  File "C:\Users\user\Miniconda3\envs\mssdev\lib\site-packages\git\refs\symbolic.py", line 397, in log_append
    return RefLog.append_entry(committer_or_reader, RefLog.path(self), oldbinsha,
  File "C:\Users\user\Miniconda3\envs\mssdev\lib\site-packages\git\refs\log.py", line 272, in append_entry
    lf._obtain_lock_or_raise()
  File "C:\Users\user\Miniconda3\envs\mssdev\lib\site-packages\git\util.py", line 834, in _obtain_lock_or_raise
    raise IOError("Lock for file %r did already exist, delete %r in case the lock is illegal" %
OSError: Lock for file 'C:\\Users\\user\\colabdata\\filedata\\dd\\.git\\logs\\HEAD' did already exist, delete 'C:\\Users\\user\\colabdata\\filedata\\dd\\.git\\logs\\HEAD.lock' in case the lock is illegal
```

**Comment by ReimarBauer** [comment]
reopen when we have more details
